<?php

/**
 * Carreras y programas de estudio.
 *
 * @return array<int, string>
 */
return [
    'Actuación y Teatro',
    'Actuario',
    'Administración De Autotransporte y Logística',
    'Administración de Empresas de Servicios',
    'Administración de Empresas e Ing. Asociadas',
    'Administración de Empresas Turísticas',
    'Administración de Hoteles y Restaurantes',
    'Administración de Negocios Internacionales',
    'Administración de Predios Agrícolas',
    'Administración de Procesos Productivos',
    'Administración de Ventas',
    'Administración Empresas en Marketing y Comunicación Digital',
    'Administración en Alimentación Colectiva',
    'Administración Financiera',
    'Administración gastronómica',
    'Administración Gastronómica Internacional',
    'Administración Hotelera Internacional',
    'Administración Hotelera Profesional',
    'Administración Industrial',
    'Administración Pública',
    'Administración Turística y Hotelera',
    'Administración y Evaluación De Proyectos',
    'Administración y Producción Agropecuaria',
    'Administrador Universitario de Empresas',
    'Agrobiotecnología',
    'Agronomía',
    'Análisis de Sistemas / Analista Programador',
    'Animación Digital',
    'Antropología',
    'Arbitro de Fútbol Profesional',
    'Arqueología',
    'Arquitectura',
    'Artes / Artes Plásticas / Artes Gráficas',
    'Artes Visuales',
    'Asistente Ejecutivo',
    'Asistente Judicial',
    'Asistente Social',
    'Astronomía',
    'Auxiliar Paramédico',
    'Bachiller en Ciencias Religiosas',
    'Bachillerato en Arte',
    'Bachillerato en Ciencias',
    'Bachillerato En Educación',
    'Bachillerato en Humanidades',
    'Bacteriología',
    'Bar Training',
    'Bibliotecología / Documentación',
    'Bioanalisis / Biotecnología Industrial',
    'Biología',
    'Biología en Gestión de Recursos Naturales',
    'Biología Marina',
    'Bioquímica',
    'Biotecnología / Bioingeniería',
    'Caligrafía Pública',
    'Canto / Interpretación en Canto',
    'Cartografía',
    'Chofer / Transporte',
    'Ciencias Físicas',
    'Ciencias Hídricas',
    'Ciencias Políticas',
    'Cine / Séptimo Arte',
    'Clasificación Arancelaria y Despacho Aduanero',
    'Comercialización',
    'Comunicación Audiovisual y/o Multimedia',
    'Comunicación Escénica',
    'Comunicación Social / Empresarial',
    'Consejería Educacional y Vocacional Enseñanza Básica',
    'Consejería Educacional y Vocacional Enseñanza Media',
    'Conservación Industrial de Alimentos por Frío',
    'Construcción Civil',
    'Construcciones Metálicas',
    'Contactología',
    'Contador Auditor',
    'Contador Público y Auditor',
    'Control de Gestión',
    'Cosmetología',
    'Creación e Interpretación Musical',
    'Danza / Interpretación en Danza',
    'Decoración de Interiores',
    'Derecho',
    'Dibujo de Proyectos de Arquitectura e Ingenieria',
    'Dibujo Industrial',
    'Dibujo Técnico',
    'Dibujo y Proyectos Industriales',
    'Diplomado',
    'Dirección de Arte',
    'Dirección y Producción',
    'Dirección y Producción de eventos',
    'Diseño',
    'Diseño de Interiores / Decoración',
    'Diseño de Interiores y Mobiliario',
    'Diseño de Objetos y Ambientes',
    'Diseño de Vestuario',
    'Diseño Digital',
    'Diseño Editorial',
    'Diseño Gráfico',
    'Diseño Industrial',
    'Diseño y Producción de Areas Verdes',
    'Diseño y Producción Industrial',
    'Diseño y Programación Multimedia / Diseño Digital',
    'Doctorado',
    'Doctorado Ciencias de la Educación',
    'Ecología',
    'Economía',
    'Educación Física',
    'Electromecánico',
    'Electrónica',
    'Electrónica de Sistemas Computarizados',
    'Enfermería',
    'Enseñanza Media o Superior',
    'Escenografía',
    'Escultura',
    'Estadísticas',
    'Estudios espaciales',
    'Filosofía',
    'Finanzas Bancarias / Negocios Internacionales',
    'Física / Ciencias Físicas',
    'Fisioterapia',
    'Fonoaudiología',
    'Fotografía',
    'Frigorista Electromecánico',
    'Fuerzas Armadas / Milicia',
    'Gasfitería',
    'Gastronomía / Cocina',
    'Geofísica',
    'Geografía',
    'Geología',
    'Geomensura / Topografía / Agrimensura',
    'Geominería',
    'Geoquímica',
    'Guardia de Seguridad',
    'Higienista Dental',
    'Historia / Licenciatura en Historia',
    'Historia del Arte',
    'Historia y Geografía',
    'Hotelería / Administración Hotelera',
    'Idiomas',
    'Ilustración Digital',
    'Informática',
    'Informática Biomédica',
    'Ingenieria Civil en Sonido',
    'Ingenieria en Biotecnología',
    'Ingenieria en Comercio / Negocio Internacional',
    'Ingenieria en RRHH',
    'Ingeniería',
    'Ingeniería Aerospacial / Aeronáutica',
    'Ingeniería Agrícola',
    'Ingeniería Agropecuaria',
    'Ingeniería Biomédica',
    'Ingeniería Bioquímica',
    'Ingeniería Civil',
    'Ingeniería civil ambiental',
    'Ingeniería Civil Eléctrica',
    'Ingeniería Civil Electrónica',
    'Ingeniería Civil en Agroindustrias',
    'Ingeniería Civil en Computación e Informática',
    'Ingeniería Civil en Electricidad',
    'Ingeniería Civil en Energías Renovables',
    'Ingeniería Civil en Minas',
    'Ingeniería Civil en Obras Civiles',
    'Ingeniería Civil Industrial',
    'Ingeniería Civil Matemática',
    'Ingeniería Civil Mecánica',
    'Ingeniería Civil Metalúrgica',
    'Ingeniería Civil Química',
    'Ingeniería Comercial',
    'Ingeniería Computación Informática y Comunicaciones',
    'Ingeniería de Diseño / Automatización Electrónica',
    'Ingeniería de Ejecución en Administración',
    'Ingeniería de Ejecución en Administración Hotelera',
    'Ingeniería de Ejecución en Administración Turística',
    'Ingeniería de Ejecución en Mecánica Automotriz y Autotrónica',
    'Ingeniería de Ejecución Industrial',
    'Ingeniería de Petróleos / Petroquímica',
    'Ingeniería de Producción',
    'Ingeniería de Sistemas de Información Empresarial y Control de Gestión',
    'Ingeniería Diseño de Productos',
    'Ingeniería Ejecución Administración de Empresas',
    'Ingeniería Ejecución en Gestión Industrial',
    'Ingeniería Ejecución Web Manager',
    'Ingeniería Electrónica',
    'Ingeniería en Acuicultura y Pesca',
    'Ingeniería en Administración Agroindustrial',
    'Ingeniería en Administración de Empresas',
    'Ingeniería en Administración de Operaciones',
    'Ingeniería en Administración Hotelera Internacional',
    'Ingeniería en Administración Industrial',
    'Ingeniería en Agronegocios',
    'Ingeniería en Agronomía',
    'Ingeniería en Alimentos',
    'Ingeniería en Automatización y Control Industrial',
    'Ingeniería en Automatización y Robótica',
    'Ingeniería en Aviación Comercial',
    'Ingeniería en Bioinformática',
    'Ingeniería en Bioprocesos',
    'Ingeniería en Climatización',
    'Ingeniería en Computación',
    'Ingeniería en Computación e Informática',
    'Ingeniería en Conectividad y Redes',
    'Ingeniería en Construcción',
    'Ingeniería en Construcción Civil',
    'Ingeniería en Control de Gestión',
    'Ingeniería en Control e Instrumentación Industrial',
    'Ingeniería en Deportes',
    'Ingeniería en Ejecución Eléctrica',
    'Ingeniería en Ejecución Electrónica',
    'Ingeniería en Ejecución Mecánica',
    'Ingeniería en Electricidad',
    'Ingeniería en Estadística',
    'Ingeniería en Fabricación y montaje Ind.',
    'Ingeniería en Física',
    'Ingeniería en Geografía',
    'Ingeniería en Geomensura',
    'Ingeniería en Gestión',
    'Ingeniería en Gestión de Calidad y Ambiente',
    'Ingeniería en Gestión de Negocios',
    'Ingeniería en Gestión e Informática',
    'Ingeniería en Gestión Turística',
    'Ingeniería en Gestión y Control de Calidad',
    'Ingeniería en Gestión y Desarrollo Tecnológico',
    'Ingeniería en Industrias de la Madera',
    'Ingeniería en Información y Control de Gestión',
    'Ingeniería en Informática / Sistemas',
    'Ingeniería en Logística',
    'Ingeniería en Mantenimiento Industrial',
    'Ingeniería en manufactura industrial',
    'Ingeniería en Maquinaria y Vehículos Automotrices',
    'Ingeniería en Marina Mercante',
    'Ingeniería en Marketing',
    'Ingeniería en Mecatrónica',
    'Ingeniería en Medio Ambiente',
    'Ingeniería en Metalmecánica',
    'Ingeniería en Minas y Metalúrgia',
    'Ingeniería en Ordenación Ambiental',
    'Ingeniería en Prevención de Riesgos',
    'Ingeniería en procesos de la madera',
    'Ingeniería en Proyectos Industriales',
    'Ingeniería en Recursos Humanos',
    'Ingeniería en Recursos Naturales',
    'Ingeniería en Recursos Naturales Renovables',
    'Ingeniería en Refrigeración y Climatización',
    'Ingeniería en Sonido',
    'Ingeniería en Telecomunicaciones',
    'Ingeniería en Telemática',
    'Ingeniería en Transporte',
    'Ingeniería en transporte marítimo',
    'Ingeniería en Turismo y Hotelería',
    'Ingeniería Forestal',
    'Ingeniería Geomática',
    'Ingeniería Hidráulica',
    'Ingeniería Industrial',
    'Ingeniería Matemáticas',
    'Ingeniería Mecánica',
    'Ingeniería Mecánica en Producción Industrial',
    'Ingeniería Pesquera / Cultivos Marinos',
    'Ingeniería Química',
    'Ingeniería Textil',
    'Ingeniero Naval',
    'Instrumentación Quirúrgica',
    'Intercambio',
    'Jardinería / Floricultura',
    'Junior / Cadete / Oficinista',
    'Kinesiología',
    'Laboratorio Dental / Mecánica Dental',
    'Laboratorista Químico Minero',
    'Letras',
    'Licenciatura',
    'Licenciatura en Archivología',
    'Licenciatura en Arte / Bellas Artes',
    'Licenciatura en Artes Visuales',
    'Licenciatura en Ciencias Biológicas',
    'Licenciatura en Ciencias del Medio Ambiente',
    'Licenciatura en Ciencias Religiosas y Estudios Eclesiásticos',
    'Licenciatura en Computación',
    'Licenciatura en Educación / Magisterio',
    'Licenciatura en Filosofía',
    'Licenciatura en Física',
    'Licenciatura en Gestión de Medios y Entretenimiento',
    'Licenciatura en Literatura / Literatura / Letras',
    'Licenciatura en Matemática',
    'Licenciatura en Producción de Bio-Imágenes',
    'Licenciatura en Química',
    'Licenciatura en Recursos Humanos',
    'Licenciatura en Seguridad e Higiene en el Trabajo',
    'Licenciatura en Tecnología educativa',
    'Licenciatura nivel inicial',
    'Locución y Conducción de Radio y TV',
    'Maestría en Dirección Comercial',
    'Maestro Mayor de Obras',
    'Magister',
    'Magister en Ciencias de la Educación',
    'Magíster en Historia',
    'Magíster en Lingüística',
    'Manteniemiento de Maquinaria Pesada',
    'Mantenimiento de Maquinaria de Planta',
    'Marketing',
    'Martillero y Corredor Público',
    'Matemática',
    'Matrón (a)',
    'Mayordomo',
    'MBA',
    'MBA Ejecutivo',
    'MBA Joven Profesional',
    'MBA Profesional Internacional',
    'Mecánica',
    'Mecatrónica',
    'Medicina',
    'Medicina Veterinaria',
    'Metálica y Autopartes',
    'Meteorología',
    'Microbiología industrial de alimentos',
    'Modelista de Vestuario',
    'Museología',
    'Música',
    'Músico - Terapia',
    'Musicoterapia',
    'Negocios Internacionales',
    'Notario Público / Escribano Público',
    'Nutrición y Alimentación Institucional',
    'Nutrición y Dietética',
    'Obstetricia y Puericultura',
    'Oceanografía',
    'Odontología',
    'Oftalmología',
    'Operador De Equipos Móviles',
    'Optica',
    'Optometría',
    'Orfebrería / Joyería',
    'Orientación Familiar',
    'Otra carrera',
    'Paisajismo / Diseño de Paisaje',
    'Panadero',
    'Paramédico',
    'Pastelería Internacional',
    'Pedagogía',
    'Pedagogía Educación Media en Lenguaje y Comunicación',
    'Pedagogía en Biología y Ciencias Naturales',
    'Pedagogía en Ciencias',
    'Pedagogía en Cs. Naturales y Física',
    'Pedagogía en Cs. Naturales y Química',
    'Pedagogía en Educación Básica',
    'Pedagogía en Educación de Párvulos',
    'Pedagogía en Educación Diferencial',
    'Pedagogía en Educación Física y Deporte',
    'Pedagogía en Español',
    'Pedagogía en Filosofía',
    'Pedagogía en Historia, Geografía y Ciencias Sociales',
    'Pedagogía en Idiomas',
    'Pedagogía en Lengua Castellana y Comunicación',
    'Pedagogía en Lenguaje y Literatura',
    'Pedagogía en Matemáticas / Computación',
    'Pedagogía en Música / Arte',
    'Pedagogía en Religión',
    'Pedagogía Media / Educación Media / Secundaria',
    'Pedagogía Media en Religión y Educación Moral',
    'Peluquería',
    'Periodismo',
    'Periodismo Deportivo',
    'Perito Criminalístico',
    'Piloto / Aviación',
    'Pintura',
    'Preparador Físico',
    'Prevención de Riesgos / Seguridad Industrial',
    'Procesos Agroindustriales',
    'Procesos De Producción',
    'Producción Gastronómica',
    'Producción Musical',
    'Programación',
    'Psicología',
    'Psicología Clínica',
    'Psicología Educacional',
    'Psicología Laboral',
    'Psicopedagogía',
    'Publicidad',
    'Publicidad Profesional Mención Marketing y Medios',
    'Publicidad Técnica Mención Marketing Promocional',
    'Puericultura',
    'Química',
    'Química De Materiales',
    'Química Industrial',
    'Química Marina',
    'Química y Farmacia',
    'Químico Laboratista Industrial',
    'Quiropraxia',
    'Recursos Humanos / Relaciones Industriales',
    'Relaciones del Trabajo',
    'Relaciones Internacionales',
    'Relaciones Públicas',
    'Sacerdocio',
    'Secretariado',
    'Secretariado Bilingue',
    'Servicios Domésticos',
    'Servicios Posventa Área Automotriz',
    'Sevicios Domésticos / Empleada Doméstica',
    'Sistemas de Gestión de la Calidad',
    'Socioeconomía',
    'Sociología',
    'Técnico / Tecnólogo / Técnico Superior',
    'Técnico agente o visitador médico',
    'Técnico agropecuario',
    'Técnico Asistente del Educador de Párvulos',
    'Técnico asistente del educador diferencial',
    'Técnico Cinematográfico',
    'Técnico de Nivel Sup. en Contacto con la Naturaleza y Deporte Aventura',
    'Técnico de Nivel Sup. en Guía Turístico en la Naturaleza',
    'Técnico de Nivel Superior en Actividad Física y Deportes',
    'Técnico de Nivel Superior en Administración de Negocios Gastronómicos',
    'Técnico de Nivel Superior en Bioprocesos Industriales',
    'Técnico de Nivel Superior en Computación',
    'Técnico de Nivel Superior en Organización y Producción de Eventos',
    'Técnico de Nivel Superior en Vitivinicultura y Enología',
    'Técnico de Radiología y Radioterapia',
    'Técnico Dental y Asistente de Odontología',
    'Técnico en acuicultura y pesca',
    'Técnico en Administración de Empresas',
    'Técnico en Administración de Programas Sociales',
    'Técnico en Administración de Recursos Humanos y Personal',
    'Técnico en Administración de Redes y Soporte',
    'Técnico en alimentos',
    'Técnico en Arte y Gestión Cultural',
    'Técnico En Bienestar Social',
    'Técnico en Climatización',
    'Técnico en Comercio Exterior',
    'Técnico en Computación e Informática',
    'Técnico en Comunicación Audiovisual',
    'Técnico en Comunicación para las Organizaciones Sociales',
    'Técnico en Construcción y Obras Civiles',
    'Técnico en Contabilidad General',
    'Técnico en control de calidad',
    'Técnico en Deporte, Recreación y Preparación Física',
    'Técnico en Diseño de Espacios y Equipamientos',
    'Técnico en Diseño editorial',
    'Técnico en Diseño Gráfico',
    'Técnico en Economía y Administración de la pequeñas y mediana empresa',
    'Técnico en Edificación',
    'Técnico en Electricidad Industrial',
    'Técnico en Electricidad y Electricidad Industrial',
    'Técnico en Electrónica y Electrónica Industrial',
    'Técnico en Enfermería',
    'Técnico en Fabricación y montaje Industrial',
    'Técnico en Farmacia',
    'Técnico en Geología',
    'Técnico en Geomensura',
    'Técnico en geominería',
    'Técnico en Gestión y Control de calidad',
    'Técnico en Instrumentación, Automatización y Control Industrial',
    'Técnico en Laboratorio Clínico',
    'Técnico en Logística',
    'Técnico en Mantención',
    'Técnico en Mantenimiento Industrial',
    'Técnico en Masoterapia',
    'Técnico en Matricería',
    'Técnico en Mecánica',
    'Técnico en Mecánica Automotriz',
    'Técnico en Mecánica Industrial',
    'Técnico en Medio Ambiente',
    'Técnico en Metalmecánica',
    'Técnico en Minería y Metalúrgica',
    'Técnico en Oleohidráulica y Neumática',
    'Técnico en óptica',
    'Técnico en peluquería y estética',
    'Técnico en Planificación Vial',
    'Técnico en Podología',
    'Técnico en Prevención de Riesgos',
    'Técnico en Procesos de la madera',
    'Técnico en procesos industriales',
    'Técnico en Producción y realización de medios masivos',
    'Técnico en Química (Análisis e Industrial)',
    'Técnico en Refrigeración',
    'Técnico en Rehabilitación Psicosocial, Alcohol y Drogas',
    'Técnico en Restauración',
    'Técnico en Salud Natural y Terapias Complementarias',
    'Técnico en Servicio Social',
    'Técnico en Sonido',
    'Técnico en Soporte Computacional',
    'Técnico en Telemática',
    'Técnico en terapias naturales y naturopatía',
    'Técnico en Topografia',
    'Técnico en Trabajo Social',
    'Técnico en traducción e interpretariado',
    'Técnico en Transporte Marítimo y Puertos',
    'Técnico en Tránsito y Transporte',
    'Técnico en Turismo y Hotelería',
    'Técnico Financiero',
    'Técnico Jurídico',
    'Técnico Marino',
    'Técnico Nivel Medio Naval',
    'Técnico Nivel Superior Naval',
    'Técnico Ortesista',
    'Técnico Ortoprotesista',
    'Técnico Productor en Medios Visuales',
    'Técnico Profesional Archivero',
    'Técnico Superior en administración cooperativa y mutual',
    'Técnico Superior en Administración Agrícola',
    'Técnico Superior en Bromatología',
    'Técnico Universitario en Telecomunicaciones y Redes',
    'Técnico Veterinario',
    'Tecnología en Escenografía',
    'Tecnología en gestión Forestal',
    'Tecnología En Ilustración',
    'Tecnología en Metalurgia',
    'Tecnología en Minería y Metalurgía',
    'Tecnología Forestal',
    'Tecnología Industrial de alimentos del mar',
    'Tecnología Industrial de la madera',
    'Tecnología Industrial de los alimentos',
    'Tecnología Médica',
    'Tecnología Pecuaria',
    'Tecnología y Administración Agrícola',
    'Tecnología y Administración Pecuaria',
    'Tecnologías De La Información y Comunicación',
    'Tecnólogo / Técnico Control Industrial',
    'Tecnólogo / Técnico en Construcción',
    'Teología',
    'Terapia Física',
    'Terapia Ocupacional',
    'Trabajo Social',
    'Traducción e Interpretación',
    'Tripulante de Cabina / Azafata(o)',
    'Turismo de Aventura',
    'Turismo Técnico Mención Empresas de Viajes',
    'Turismo Técnico Mención Tráfico y Carga Aérea',
    'Urbanismo',
    'Venta y Publicidad',
    'Zootecnia / Zoología',
];
