<?php

// Catálogo de habilidades (software/herramientas y competencias generales).
// Generado desde habilidades.csv; deduplicado por forma normalizada.

return [
    '3com',
    '3dec',
    '3ds Max',
    '5S',
    '800xa',
    'A2',
    'Aasidra',
    'Abacus',
    'Abap',
    'Abaqus',
    'Abastecimiento',
    'Abbyy Finereader',
    'Abies',
    'Ableton Live',
    'Abril',
    'Acad',
    'Accountability',
    'Accpac',
    'ACD Systems',
    'Acdsee',
    'Acepta',
    'Aceptable',
    'Acl',
    'Aconex',
    'Acquire',
    'Acronis',
    'Actionscript',
    'Actitud de servicio',
    'Actitud De Servicio Al Cliente',
    'Actitud Positiva',
    'Actitud Proactiva',
    'Active Directory',
    'ActivInspire',
    'Actix',
    'Actualhotel',
    'Acuario',
    'Acucobol',
    'Acunetix',
    'Ad Aware',
    'Adabas',
    'Adaco',
    'Adaia',
    'Adam',
    'Adapi',
    'Adaptabilidad',
    'Adaptabilidad a Los Cambios',
    'Adaptación Rápida',
    'Adaptapro',
    'Adaxx',
    'Adcam',
    'Addax',
    'Adecom',
    'Adempiere',
    'Adexus',
    'Adina',
    'Adirace',
    'Admedif',
    'Admetricks',
    'Admicorp',
    'Administración',
    'Administración De Contratos',
    'Administración De Empresas',
    'Administración De Personal',
    'Administración De Proyectos',
    'Administración De Recursos',
    'Administración de Redes',
    'Administración De Servidores',
    'Administración Del Tiempo',
    'Administración Logística',
    'Administración Remota',
    'Administrar',
    'Administrativas',
    'Administrativo/a',
    'Adminpaq',
    'Adminplus',
    'Admintour',
    'Adobe Acrobat',
    'Adobe After Effects',
    'Adobe After Effects CC',
    'Adobe After Effects CS6',
    'Adobe Audition',
    'Adobe Captivate',
    'Adobe Creative Suite',
    'Adobe Cs',
    'Adobe Cs3',
    'Adobe Cs4',
    'Adobe Cs5',
    'Adobe Cs6',
    'Adobe Dreamweaver',
    'Adobe Dreamweaver Cs3',
    'Adobe Dreamweaver Cs4',
    'Adobe Dreamweaver Cs5',
    'Adobe Dreamweaver Cs6',
    'Adobe Encore',
    'Adobe Fireworks',
    'Adobe Flash',
    'Adobe Flash Cs3',
    'Adobe Flash Cs4',
    'Adobe Flash Cs5',
    'Adobe Flash Cs6',
    'Adobe Flex',
    'Adobe FreeHand',
    'Adobe Golive',
    'Adobe Illustrator',
    'Adobe Illustrator Cc',
    'Adobe Illustrator Cs',
    'Adobe Illustrator Cs3',
    'Adobe Illustrator Cs4',
    'Adobe Illustrator Cs5',
    'Adobe Illustrator Cs6',
    'Adobe Image Ready',
    'Adobe InDesign',
    'Adobe Indesign Cc',
    'Adobe Indesign Cs3',
    'Adobe Indesign Cs4',
    'Adobe Indesign Cs5',
    'Adobe Indesign Cs6',
    'Adobe Lightroom',
    'Adobe Master Collection',
    'Adobe Muse',
    'Adobe Page Maker',
    'Adobe Pagemaker',
    'Adobe Pdf',
    'Adobe Photoshop',
    'Adobe Photoshop 7.0',
    'Adobe Photoshop Cc',
    'Adobe Photoshop Cs',
    'Adobe Photoshop Cs2',
    'Adobe Photoshop Cs3',
    'Adobe Photoshop Cs4',
    'Adobe Photoshop Cs5',
    'Adobe Photoshop Cs6',
    'Adobe Premiere Cc',
    'Adobe Premiere Cs6',
    'Adobe Premiere Pro',
    'Adobe Premiere Pro Cc',
    'Adobe Premiere Pro Cs6',
    'Adobe Soundbooth',
    'Adobe Suite Cc',
    'Adobe Suite Cs5',
    'Adobe Suite Cs6',
    'Adobe Xd',
    'Adonis',
    'Adonline',
    'Adquira',
    'Adquisiciones',
    'Adsl',
    'Aduananet',
    'Advertmind',
    'Advisor',
    'Adwords',
    'Aegisub',
    'Aermod',
    'Aezo',
    'Afable',
    'Aft Arrow',
    'Agenda Médica',
    'Aggflow',
    'Agi32',
    'Ágil',
    'Agile',
    'Agilidad',
    'Agisoft',
    'Agisoft Photoscan',
    'Agro 2000',
    'Agro2000',
    'Agrodata',
    'Agroprime',
    'Agrosig',
    'Agrosoft',
    'Agrowin',
    'Aheeva',
    'Aimms',
    'Aimsum',
    'Aimsun',
    'Airbox',
    'Airh',
    'Airnav',
    'Airviro',
    'Aix',
    'Ajax',
    'Akva',
    'Alcatel',
    'Alcohol 120',
    'Aldon',
    'Alegre',
    'Aleph',
    'Alerce',
    'Alert',
    'Alertran',
    'Alexandría',
    'Alfresco',
    'Algor',
    'Alias',
    'Alkym',
    'Allegro',
    'Allen Bradley',
    'Allplan',
    'Allsys',
    'Alm',
    'Alm11',
    'Alma',
    'Alogit',
    'Aloha',
    'Alpha',
    'Alpro',
    'Alta Capacidad Analítica',
    'Alta Capacidad De Adaptación',
    'Alta Capacidad De Análisis',
    'Alta Capacidad De Aprendizaje',
    'Alta Capacidad De Gestión',
    'Alta Capacidad De Liderazgo',
    'Alta Capacidad De Negociación',
    'Alta Capacidad De Trabajo Bajo Presión',
    'Alta Capacidad De Trabajo en Equipo',
    'Alta Capacidad Para Trabajar Bajo Presión',
    'Alta Capacidad Para Trabajar en Equipo',
    'Alta Capacidad Resolutiva',
    'Alta Motivación',
    'Alta Motivación Al Logro',
    'Alta Orientación Al Cliente',
    'Alta Responsabilidad',
    'Alta Tolerancia a La Frustración',
    'Alta Tolerancia Al Trabajo Bajo Presión',
    'Altagestion',
    'Altair',
    'Altamira',
    'Altanet',
    'Altea',
    'Alteryx',
    'Altiris',
    'Altitud',
    'Altitude',
    'Altium',
    'Alto Compromiso',
    'Alto Grado De Compromiso',
    'Alto Grado De Responsabilidad',
    'Alto Nivel De Aprendizaje',
    'Alto Nivel De Compromiso',
    'Alto Sentido De La Responsabilidad',
    'Alto Sentido De Responsabilidad',
    'Altos',
    'Amabilidad',
    'Amable',
    'Amadeus',
    'Amadeus Vista',
    'Amdocs',
    'Amicar',
    'Amigable',
    'Amos',
    'Ampl',
    'Amt',
    'Análisis',
    'Análisis Crítico',
    'Análisis De Cuentas',
    'Análisis De Datos',
    'Análisis De Datos Cuantitativos',
    'Análisis De Estados Financieros',
    'Análisis De Fallas',
    'Análisis De Información',
    'Análisis De Mercado',
    'Análisis De Negocio',
    'Análisis De Problemas',
    'Análisis De Procesos',
    'Analisis de sistemas',
    'Análisis Estadístico',
    'Análisis Financiero',
    'Análisis Numérico',
    'Análisis Químico',
    'Analista De Datos',
    'Analítico/a',
    'Analyst',
    'Analytica',
    'Analytics',
    'Android SDK',
    'Angular',
    'Angularjs',
    'Animate',
    'Anita',
    'Answer Tree',
    'Ansys',
    'Antara',
    'Antares',
    'Antenas',
    'Antirion',
    'Antispam',
    'Anylogic',
    'Anzio',
    'Apache',
    'Apache Tomcat',
    'Apasionado/a',
    'Aperture',
    'Aplicada',
    'Apnet',
    'Apollo',
    'Apolo',
    'Apple Macintosh',
    'Appserv',
    'Aprender',
    'Aprender Rápido',
    'Aprendizaje',
    'Aprendizaje Autónomo',
    'Aprendizaje Constante',
    'Aprendizaje Continúo',
    'Aprendizaje Permanente',
    'Aprendizaje Rápido',
    'Aprendo Con Facilidad',
    'Aprendo Con Rapidez',
    'Aprendo Muy Rápido',
    'Aprendo Rápido',
    'Aptana',
    'Aptitudes De Liderazgo',
    'Aquachem',
    'Aquafarmer',
    'Aquasim',
    'Aquatool',
    'Aquifertest',
    'Aquila',
    'Aramis',
    'Aranda',
    'Arbor',
    'ArcGIS',
    'Arcgis 10',
    'Arcgis 10.1',
    'Arcgis 10.2',
    'Arcgis 10.3',
    'Arcgis 9.2',
    'Arcgis 9.3',
    'Arcgis10',
    'Archicad',
    'Arcinfo',
    'Arcmap',
    'Arcpad',
    'Arcserve',
    'Arcserver',
    'Arcsig',
    'Arcsight',
    'Arcview',
    'Arcview 3.2',
    'Arcview Gis',
    'Arcview Gis 3.2',
    'Arcview3 2',
    'Arduino',
    'Arena 7.0',
    'Arena Simulation',
    'Arena Simulator',
    'Arenas',
    'Ares',
    'Argis',
    'Argouml',
    'Argus',
    'Ariba',
    'Aris',
    'Arlequin',
    'Armado/Configuración de Computadores',
    'Arpon',
    'Arquímedes',
    'Arquitectura',
    'Artcam',
    'Artcut',
    'Artemis',
    'Arthur',
    'Articulate',
    'Articulate Storyline',
    'Artikos',
    'Artioscad',
    'Artisan',
    'Artisteer',
    'Artlantis',
    'Arto',
    'Arview',
    'As 2',
    'As 400',
    'As2',
    'As400',
    'As400a',
    'As400c',
    'Asana',
    'Asc Horarios',
    'Aseo',
    'Asertividad',
    'Asertivo/a',
    'Asesoría',
    'Asicam',
    'Asicom',
    'Asigen',
    'Asisco',
    'Asisscad',
    'Asistente',
    'Asistente Administrativo',
    'Askia',
    'Asone',
    'Asp',
    'Asp .net',
    'Asp 3.0',
    'Asp Net',
    'Asp.net',
    'Asp.net C#',
    'Asp.net Mvc',
    'Aspect',
    'Aspel',
    'Aspen',
    'Aspx',
    'Asr',
    'Assembler',
    'Assembly',
    'Asset',
    'Assiscad',
    'Asterisk',
    'Asterix',
    'Astor',
    'Atenas',
    'Atención',
    'Atención a Cliente',
    'Atención a Clientes',
    'Atención a Los Detalles',
    'Atención a Público',
    'Atención Al Cliente',
    'Atención Al Detalle',
    'Atención Al Público',
    'Atención Al Usuario',
    'Atención Clientes',
    'Atención De Clientes',
    'Atención De Público',
    'Atención Telefónica',
    'Atenea',
    'Atento/a',
    'Atentus',
    'Atis',
    'Atlantis',
    'Atlas',
    'Atlas Ti',
    'Atlas. Ti',
    'Atlasti',
    'Atm',
    'Atoll',
    'Atom',
    'Atp',
    'Atpco',
    'Atpdraw',
    'Audaces',
    'Audacity',
    'Audatex',
    'Audaz',
    'Audisoft',
    'Auditoría',
    'Auditoria Interna',
    'Auge',
    'Aura',
    'Auranet',
    'Auraportal',
    'Auris',
    'Aurora',
    'Autentia',
    'Autentica',
    'Authorware',
    'Auto Aprendizaje',
    'Auto Cad',
    'Auto Cad 2007',
    'Auto Cad 2d',
    'Auto Cad 2d y 3d',
    'Auto Cad Civil 3d',
    'Auto Confianza',
    'Auto Conocimiento',
    'Auto Critico/a',
    'Auto Data',
    'Auto Disciplina',
    'Auto Exigencia',
    'Auto Exigente',
    'Auto Motivación',
    'Auto3p',
    'Autoaudit',
    'Autocad',
    'Autocad 14',
    'Autocad 2000',
    'Autocad 2002',
    'Autocad 2004',
    'Autocad 2005',
    'Autocad 2006',
    'Autocad 2007',
    'Autocad 2008',
    'Autocad 2009',
    'Autocad 2010',
    'Autocad 2011',
    'Autocad 2012',
    'Autocad 2013',
    'Autocad 2014',
    'Autocad 2015',
    'Autocad 2016',
    'Autocad 2017',
    'Autocad 2018',
    'Autocad 2d',
    'Autocad 2d y 3d',
    'Autocad 3d',
    'Autocad Civil',
    'Autocad Civil 3d',
    'Autocad Electrical',
    'Autocad Land',
    'Autocad Land Development',
    'Autocad Map',
    'Autocad Mechanical',
    'Autocad Plant 3d',
    'Autocad R14',
    'Autocar',
    'Autocontrol',
    'Autocrítico/a',
    'Autodata',
    'Autodesk',
    'Autodesk Architectural Desktop',
    'Autodesk Autocad',
    'Autodesk Civil 3d',
    'Autodesk Inventor',
    'Autodesk Inventor Profesional',
    'Autodesk Inventor Professional',
    'Autodesk Maya',
    'Autodesk Navisworks',
    'Autodesk Revit',
    'Autodesk Revit Architecture',
    'Autodidacta',
    'Autogestión',
    'Autogestión e Iniciativa',
    'Autoit',
    'Autoline',
    'Autolisp',
    'Automation',
    'Automation Studio',
    'Automationstudio',
    'Automatización',
    'Automatización De Procesos',
    'Automatización Industrial',
    'Autonomía',
    'Autonomía y proactividad',
    'Autónomo/a',
    'Autopipe',
    'Autoplant',
    'Autopro',
    'Autopro 2000',
    'Autopro2000',
    'Autosuficiente',
    'Autosystem',
    'Autoturn',
    'Avantis',
    'Avid',
    'Avid Media Composer',
    'Avid Newscutter',
    'Avid Xpress Pro',
    'Avis',
    'Avwin',
    'Avwin98',
    'Awesim',
    'Awesin',
    'Awk',
    'Aws',
    'Ax',
    'Axapta',
    'Axis',
    'Axure',
    'Azure',
    'B2b',
    'B3000',
    'Baan',
    'Baan Erp',
    'Babylon Translator',
    'BAC',
    'Backend',
    'Backoffice',
    'Backtrack',
    'Backup',
    'Bacula',
    'Badico',
    'Bajo Presión',
    'Balance Scorecard',
    'Balanced Scorecard',
    'Balsamiq',
    'Balsamiq Mockups',
    'Bancomex',
    'Banktrade',
    'Bann',
    'Banner',
    'Bantotal',
    'Barista',
    'Barracuda',
    'Bartender',
    'Base De Datos',
    'Base24',
    'Basecamp',
    'Bases De Datos',
    'Bash',
    'Basis',
    'Basware',
    'Batch',
    'Bbdd',
    'Bdclass',
    'Bdgeo',
    'Bea Weblogic',
    'Beetrack',
    'Bejerman',
    'Belco',
    'Beltstat',
    'Benlar',
    'Bentley',
    'Bestfit',
    'Betonmatic',
    'Bettersoft',
    'Bi',
    'Big Data',
    'Bigdata',
    'Bigsa',
    'Bigticket',
    'Bim',
    'Bioedit',
    'Biogeme',
    'Bioinformática',
    'Biología Molecular',
    'Biometria',
    'Biosign',
    'Biosing',
    'Bioslis',
    'Biowin',
    'Bisar',
    'Bisoft',
    'Bitbucket',
    'Bitware',
    'Bizagi',
    'Biztalk',
    'Blackberry',
    'Blackboard',
    'Blackline',
    'Blast',
    'Blastplan',
    'Blastware',
    'Blender',
    'Blockchain',
    'Blocksim',
    'Blog',
    'Blogger',
    'Blogs',
    'Blogspot',
    'Bloomberg',
    'Bluecoat',
    'Bluej',
    'Boardmaker',
    'Bodega',
    'Bodeguero',
    'Bonitasoft',
    'Booking',
    'Bootstrap',
    'Borland C++',
    'Borland Delphi',
    'Boss',
    'Bpcs',
    'Bpel',
    'Bpm',
    'Bpmn',
    'Bpms',
    'Bpwin',
    'Brackets',
    'Brand',
    'Branding',
    'Brandmetric',
    'Bricscad',
    'Bridge',
    'Brio',
    'Brio Intelligence',
    'Brio Query',
    'Brioquery',
    'Browse',
    'Browser',
    'Browsers',
    'Bruno',
    'Bryce',
    'Bsale',
    'Bscs',
    'Bsoft',
    'Buen Carácter',
    'Buen Compañero',
    'Buen Comunicador',
    'Buen Desempeño en Trabajo en Equipo',
    'Buen Desempeño Laboral',
    'Buen Léxico',
    'Buen Líder',
    'Buen Manejo De Grupo',
    'Buen Manejo De Grupos',
    'Buen Manejo De Las Relaciones Interpersonales',
    'Buen Manejo De Personal',
    'Buen Manejo De Relaciones Interpersonales',
    'Buen Manejo De Trabajo en Equipo',
    'Buen Nivel De Comunicación',
    'Buen Relacionamiento',
    'Buen Trabajador en Equipo',
    'Buen Trabajo Con Los Demás',
    'Buen Trabajo en Equipo',
    'Buen Trato',
    'Buen Trato Al Cliente',
    'Buen Trato Al Usuario',
    'Buen Trato Con Clientes',
    'Buen Trato Con El Cliente',
    'Buen Trato Con El Público',
    'Buen Trato Con La Gente',
    'Buen Trato Con Las Personas',
    'Buen Trato Con Personas',
    'Buen Vocabulario',
    'Buen(a) Vendedor(a)',
    'Buena Actitud',
    'Buena Atención',
    'Buena Atención a Clientes',
    'Buena Atención Al Cliente',
    'Buena Atención Al Público',
    'Buena Capacidad De Adaptación',
    'Buena Capacidad De Aprendizaje',
    'Buena Capacidad De Comunicación',
    'Buena Capacidad De Comunicación Verbal',
    'Buena Capacidad Para Adaptarme a Los Cambios',
    'Buena Capacidad Para Adaptarse a Los Cambios',
    'Buena Compañera',
    'Buena Comunicación',
    'Buena Comunicación Con Las Personas',
    'Buena Comunicación Interpersonal',
    'Buena Comunicación Oral',
    'Buena Comunicación Verbal',
    'Buena Comunicadora',
    'Buena Dicción',
    'Buena Disponibilidad',
    'Buena Disposición',
    'Buena Disposición Para Trabajar en Equipo',
    'Buena Memoria',
    'Buena Oratoria',
    'Buena Organización',
    'Buena Ortografía',
    'Buena Para Trabajar en Equipo',
    'Buena Presencia',
    'Buena Presentación',
    'Buena Presentación Personal',
    'Buena Redacción',
    'Buena Relación Con Las Personas',
    'Buena Relación Interpersonal',
    'Buena Relación Laboral',
    'Buena Relaciones Interpersonales',
    'Buena Trabajando en Equipo',
    'Buena Voluntad',
    'Buenas Aptitudes Interpersonales',
    'Buenas Relaciones Humanas',
    'Buenas Relaciones Interpersonales',
    'Buenas Relaciones Laborales',
    'Buenas Relaciones Personales',
    'Bueno Trabajando en Equipo',
    'Buenos Modales',
    'Buffer',
    'Bugzilla',
    'BUK',
    'Business Development',
    'Business Intelligence',
    'Business Strategy',
    'Businessobjects',
    'Búsqueda De Excelencia',
    'Búsqueda De Información',
    'Búsqueda De La Excelencia',
    'Búsqueda De La Excelencia Iniciativa',
    'c Sharp',
    'c y C++',
    'C# .net',
    'C++ Builder',
    'Cableado Estructurado',
    'Cabri',
    'Cacti',
    'Cad',
    'Cadcam',
    'Cade Simu',
    'Cadena De Suministro',
    'Cadesimu',
    'Cadnaa',
    'Cadwork',
    'Cadworx',
    'Caepipe',
    'Caesar',
    'Caja',
    'Cajas',
    'Cajera',
    'Cakephp',
    'Cakewalk',
    'Calculux',
    'Calener',
    'Calidad',
    'Calidad De Servicio',
    'Calidad De Trabajo',
    'Calipso',
    'Calpuff',
    'Calypso',
    'Camaleon',
    'Camera Raw',
    'Camtasia',
    'Camtasia Studio',
    'Canela',
    'Canto',
    'Canva',
    'Canvas',
    'Capacidad Analítica',
    'Capacidad Creativa',
    'Capacidad Crítica',
    'Capacidad de actualizar los conocimientos',
    'Capacidad De Adaptabilidad',
    'Capacidad De Adaptación',
    'Capacidad De Adaptación a Cambios',
    'Capacidad De Adaptación a Los Cambios',
    'Capacidad De Adaptación Al Cambio',
    'Capacidad De Adaptarse a Los Cambios',
    'Capacidad De Análisis',
    'Capacidad De Análisis De Datos',
    'Capacidad De Análisis e Investigación',
    'Capacidad De Aprender',
    'Capacidad De Aprender Rápidamente',
    'Capacidad De Aprender Rápido',
    'Capacidad De Aprendizaje',
    'Capacidad De Aprendizaje Rápido',
    'Capacidad de aprendizaje y adaptación',
    'Capacidad De Auto Aprendizaje',
    'Capacidad De Autocrítica',
    'Capacidad De Autogestión',
    'Capacidad De Comunicación',
    'Capacidad De Comunicación Verbal',
    'Capacidad De Decisión',
    'Capacidad De Escucha',
    'Capacidad De Escuchar',
    'Capacidad De Gestión',
    'Capacidad De Iniciativa',
    'Capacidad De Iniciativa e Innovación',
    'Capacidad De Innovación',
    'Capacidad De Innovar',
    'Capacidad De Liderar',
    'Capacidad De Liderar Equipos De Trabajo',
    'Capacidad De Liderazgo',
    'Capacidad De Negociación',
    'Capacidad De Negociar',
    'Capacidad De Organización',
    'Capacidad De Organización De Trabajo',
    'Capacidad De Organización Del Trabajo',
    'Capacidad De Organización en El Trabajo',
    'Capacidad De Organizar El Trabajo',
    'Capacidad De Planificación',
    'Capacidad De Planificar',
    'Capacidad De Rápido Aprendizaje',
    'Capacidad De Relacionarme Con Los Demás',
    'Capacidad De Relacionarse Con Los Demás',
    'Capacidad De Resiliencia',
    'Capacidad De Resolución',
    'Capacidad De Resolución De Conflictos',
    'Capacidad De Resolución De Problema',
    'Capacidad De Resolución De Problemas',
    'Capacidad De Resolver Conflictos',
    'Capacidad De Resolver Problemas',
    'Capacidad De Síntesis',
    'Capacidad De Solución De Problemas',
    'Capacidad De Solucionar Problemas',
    'Capacidad De Toma De Decisiones',
    'Capacidad De Tomar Decisiones',
    'Capacidad De Trabajar Bajo Presión',
    'Capacidad De Trabajar en Equipo',
    'Capacidad De Trabajar en Grupo',
    'Capacidad De Trabajo',
    'Capacidad De Trabajo Bajo Presión',
    'Capacidad De Trabajo en Equipo',
    'Capacidad De Trabajo en Equipo Multidisciplinario',
    'Capacidad De Trabajo en Grupo',
    'Capacidad en La Toma De Decisiones',
    'Capacidad en Resolución De Problemas',
    'Capacidad en Toma De Decisiones',
    'Capacidad Organizativa',
    'Capacidad Para Adaptarme a Los Cambios',
    'Capacidad Para Adaptarse a Los Cambios',
    'Capacidad Para Aprender',
    'Capacidad Para Aprender Rápidamente',
    'Capacidad Para Desarrollar Varias Tareas a La Vez',
    'Capacidad Para El Trabajo en Equipo',
    'Capacidad Para La Resolución De Problemas',
    'Capacidad Para La Toma De Decisiones',
    'Capacidad Para Liderar',
    'Capacidad Para Liderar Equipos De Trabajo',
    'Capacidad Para Resolución De Problemas',
    'Capacidad Para Resolver Conflictos',
    'Capacidad Para Resolver Problemas',
    'Capacidad Para Solucionar Problemas',
    'Capacidad Para Toma De Decisiones',
    'Capacidad Para Tomar Decisiones',
    'Capacidad Para Trabajar Bajo Presión',
    'Capacidad Para Trabajar en Equipo',
    'Capacidad Para Trabajar en Equipos',
    'Capacidad Para Trabajo Bajo Presión',
    'Capacidad Para Trabajo en Equipo',
    'Capacidad Rápida De Aprendizaje',
    'Capacidad Resolución De Problemas',
    'Capacidad Resolutiva',
    'Capacidad Trabajo Bajo Presión',
    'Capacidad Trabajo en Equipo',
    'Capaz De Resolver Problemas',
    'Capaz De Trabajar Bajo Presión',
    'Capaz De Trabajar en Equipo',
    'Captación De Clientes',
    'Captivate',
    'Cardfive',
    'Cargonet',
    'Cargowise',
    'Carisma',
    'Carismático/a',
    'Carpintería',
    'Carrpla',
    'Cars',
    'Cartomap',
    'Cas',
    'Caschile',
    'Caseware',
    'Cassandra',
    'Castor',
    'Casys',
    'Caterpillar',
    'Cati',
    'Catia',
    'Catt Acoustic',
    'Cclas',
    'Cclass',
    'Ccleaner',
    'Ccna',
    'Ccna1',
    'Ccna2',
    'Ccnp',
    'Ccpulse',
    'Ccs',
    'Cctv',
    'Cd Creator',
    'Ce3x',
    'Cege',
    'Celtx',
    'Centinela',
    'Centos',
    'Centura',
    'Cepet',
    'Ceres',
    'Cerner',
    'Cero',
    'Certegy',
    'Certilap',
    'Ces Edupack',
    'Cespla',
    'Cgu',
    'Cguno',
    'Chamilo',
    'Change Management',
    'Changeman',
    'Changepoint',
    'Checkpoint',
    'Checksoft',
    'Chemcad',
    'Chemdraw',
    'Chemoffice',
    'Chemsketch',
    'Chemstation',
    'Chess',
    'Chesswinner',
    'Chile Compra',
    'Chilecompra',
    'Chilecompras',
    'Chileproveedores',
    'Chófer',
    'Chrome',
    'Chromeleon',
    'Chronos',
    'Chss',
    'Ciber seguridad',
    'Cibertec',
    'Cics',
    'Cimplicity',
    'Cinema',
    'Cinema 4d',
    'Cinema4d',
    'Circad',
    'Circuitmaker',
    'Cisco',
    'Cisco Ccna',
    'Cisco Ios',
    'Cisco System',
    'Cisco Systems',
    'Ciscoworks',
    'Cispro',
    'Citidirect',
    'Citoexpert',
    'Citrix',
    'Civil 3d',
    'Civil Survey',
    'Civil3d',
    'Civilcad',
    'Clarify',
    'Clarion',
    'Clarity',
    'Claroline',
    'Class',
    'Cleaner',
    'Clearcase',
    'Clearquest',
    'Clementine',
    'Clerk',
    'Clever',
    'Clic',
    'Click',
    'Clickview',
    'Cliniwin',
    'Clip',
    'Cliper',
    'Clipper',
    'Clipper 5',
    'Clipper 5.0',
    'Clipper 5.2',
    'Cliven',
    'Cliwin',
    'Clonecd',
    'Clonezilla',
    'Cloud',
    'Cloud Computing',
    'Cloudera',
    'Clustalw',
    'Clwin',
    'Cmap',
    'Cmap Tools',
    'Cmaptools',
    'Cmm',
    'Cmmi',
    'Cmms',
    'Cmnet',
    'Cmr',
    'Cms',
    'Cnc',
    'Coaching',
    'Cobis',
    'Cobit',
    'Cobol',
    'Cobra',
    'Cobralex',
    'Cobranza',
    'Cobranzas',
    'Cobtel',
    'Cocina',
    'Cocinar',
    'Coda',
    'Codeblocks',
    'Codeigniter',
    'Codesys',
    'Codisa',
    'Cognos',
    'Coin',
    'Colaboración',
    'Colaborador',
    'Colaboradora',
    'Colaborativo/a',
    'Coldfusion',
    'Colegium',
    'Color',
    'Combanc',
    'Combustion',
    'Comercial',
    'Comercio Internacional',
    'Comercionet',
    'Comet',
    'Comex',
    'Command',
    'Community Management',
    'Community Manager',
    'Compañerismo',
    'Compaq',
    'Compass',
    'Competencia',
    'Competencias Comunicativas',
    'Competencias Digitales',
    'Competente',
    'Competitividad',
    'Competitivo/a',
    'Compiere',
    'Completo',
    'Completos',
    'Compliance',
    'Compliance Tracker',
    'Composer',
    'Compras',
    'Comprensión',
    'Comprensión Interpersonal',
    'Compress',
    'Compressor',
    'Comprometida Con El Trabajo',
    'Comprometida Con Mi Trabajo',
    'Comprometido Con El Trabajo',
    'Comprometido Con Mi Trabajo',
    'Comprometido/a',
    'Compromiso',
    'Compromiso Con El Trabajo',
    'Compromiso Con La Empresa',
    'Compromiso Con La Organización',
    'Compromiso Ético',
    'Compromiso Institucional',
    'Compromiso Laboral',
    'Compromiso Organización',
    'Compromiso Social',
    'Compuagro',
    'Comscore',
    'Comshare',
    'Comsol',
    'Comunicación',
    'Comunicación Asertiva',
    'Comunicación Corporativa',
    'Comunicación Efectiva',
    'Comunicación Eficaz',
    'Comunicación Eficiente',
    'Comunicación Escrita',
    'Comunicación Estratégica',
    'Comunicación Interna',
    'Comunicación Interpersonal',
    'Comunicación Oral',
    'Comunicación Organización',
    'Comunicación Verbal',
    'Comunicación Virtual',
    'Comunicacionales',
    'Comunicaciones',
    'Comunicaciones Corporativas',
    'Comunicaciones Estratégicas',
    'Comunicaciones Internas',
    'Comunicador',
    'Comunicativas',
    'Comunicativo/a',
    'Con Ganas De Aprender',
    'Con Iniciativa',
    'Concar',
    'Concep',
    'Concept',
    'Conciencia Organización',
    'Conciliación Bancaria',
    'Conciliaciones Bancarias',
    'Conciliador',
    'Conciliadora',
    'Concur',
    'Condor',
    'Conductor',
    'Conductor Clase b',
    'Conductor Profesional',
    'Conectividad',
    'Confiabilidad',
    'Confiable',
    'Confianza',
    'Confidencialidad',
    'Configuración Hardware',
    'Conflictos',
    'Confluence',
    'Conga',
    'Conocimiento y respeto de las normas',
    'Conocimientos Administrativos',
    'Conocimientos Contables',
    'Consolas',
    'Constancia',
    'Constancia Para Lograr Objetivos',
    'Constancia Para Obtener Los Resultados Deseados',
    'Constancia Para Obtener Resultados',
    'Constante',
    'Constante Aprendizaje',
    'Construct 2',
    'Construct2',
    'Consultoría',
    'Contab',
    'Contab2000',
    'Contabilidad',
    'Contabilidad Básica',
    'Contabilidad Financiera',
    'Contaline',
    'Contaplus',
    'Contapyme',
    'Contasol',
    'Contawin',
    'Continuum',
    'Contpaq',
    'Contratos',
    'Control',
    'Control De Calidad',
    'Control De Costos',
    'Control De Gestión',
    'Control De Inventario',
    'Control De Inventarios',
    'Control De Presupuesto',
    'Control De Presupuestos',
    'Control De Procesos',
    'Control De Proyectos',
    'Control Interno',
    'Control Presupuestario',
    'Control-m',
    'Convero',
    'Conwin',
    'Cool Edit',
    'Cool Edit Pro',
    'Coolpack',
    'Cooperación',
    'Cooperador',
    'Cooperadora',
    'Cooperativo/a',
    'Cooprinsem',
    'Coordinación',
    'Coordinación De Equipos',
    'Coordinación De Equipos De Trabajo',
    'Coordinación De Proyectos',
    'Coordinador',
    'Coordinar',
    'Cordial',
    'Cordialidad',
    'Core',
    'Corel',
    'Corel Draw',
    'Corel Draw 12',
    'Corel Draw X3',
    'Corel Draw X5',
    'Corel Drawn',
    'Corel Painter',
    'Corel Photo Paint',
    'Cormix',
    'Corporate Modeler',
    'Corporater',
    'Correos',
    'Corsim',
    'Corte Certo',
    'Corvu',
    'Cosmos',
    'Cosmosworks',
    'Cpanel',
    'Cplex',
    'Creativa e Innovadora',
    'Creatividad',
    'Creatividad e Iniciativa',
    'Creatividad e Innovación',
    'Creativo e Innovador',
    'Creativo/a',
    'Crecic',
    'Credibilidad',
    'Creo',
    'Crescendo',
    'Crm',
    'Crm Dynamics',
    'Crm Sap',
    'Crm Siebel',
    'Crono',
    'Cronos',
    'Cropwat',
    'Cross',
    'Crt',
    'Crystal',
    'Crystal Ball',
    'Crystal Report',
    'Crystal Reports',
    'Crystalball',
    'Csharp',
    'Csound',
    'Css',
    'Css 3',
    'Css3',
    'Cuadratura De Caja',
    'Cubase',
    'Cubase 5',
    'Cubase Sx',
    'Cubicaciones',
    'Cucumber',
    'Cuentas Por Pagar',
    'Cultivo Celular',
    'Cumplidor',
    'Cumplimiento',
    'Cumplimiento De Metas',
    'Cumplimiento De Objetivos',
    'Cumplimiento De Plazos',
    'Curiosidad',
    'Curso Cajera Bancaria',
    'Curso Cajero Bancario',
    'Curso De Cajero Bancario',
    'Curso De Primeros Auxilios',
    'Cutmaster',
    'Cvs',
    'Cyber',
    'Cybermation',
    'Cycad',
    'Cyclepad',
    'Cyclone',
    'Cymdist',
    'Cymgrd',
    'Cymtcc',
    'Cype',
    'Cype Ingenieros',
    'Cypecad',
    'Da Vinci Resolve',
    'Dalet',
    'Dameware',
    'Danza',
    'Darma Usaha',
    'Dartfish',
    'Dashboard',
    'Data Architect',
    'Data Mining',
    'Data Protector',
    'Data Science',
    'Database',
    'Databases',
    'Datacenter',
    'Datacom',
    'Dataengine',
    'Dataflex',
    'Datamart',
    'Datamine',
    'Datamine Studio',
    'Datamining',
    'Datamodeler',
    'Datapro',
    'Dataprotector',
    'Datastage',
    'Datastream',
    'Datastudio',
    'Datasul',
    'Datatec',
    'Dataview',
    'Datawarehousing',
    'Davinci Resolve',
    'Davox',
    'Daysim',
    'Db2',
    'Dbartisan',
    'Dbase',
    'Dbdesigner',
    'Dbnet',
    'Dbs',
    'Dbsoft',
    'Dbthor',
    'Dbvisualizer',
    'Dcs',
    'Dcv',
    'De Aprendizaje Rápido',
    'De Rápido Aprendizaje',
    'Debian',
    'Decision',
    'Dedicación',
    'Dedicación Al Trabajo',
    'Dedicado/a',
    'Dedoose',
    'Deep Freeze',
    'Deepedit',
    'Deepmine',
    'Defensa Personal',
    'Defontana',
    'Delfos',
    'Delfour',
    'Delphi',
    'Delta',
    'Deltav',
    'Demandtec',
    'Dentalink',
    'Dentalsoft',
    'Dentidesk',
    'Depomod',
    'Deporte',
    'Deportes',
    'Deportista',
    'Derecho',
    'Derecho Civil',
    'Derecho Corporativo',
    'Derecho De Familia',
    'Derecho Laboral',
    'Derive',
    'Desarrollo',
    'Desarrollo De Equipos',
    'Desarrollo De Equipos De Trabajo',
    'Desarrollo De Habilidades Blandas',
    'Desarrollo De Negocios',
    'Desarrollo de páginas web',
    'Desarrollo De Personas',
    'Desarrollo De Productos',
    'Desarrollo De Proyectos',
    'Desarrollo De Software',
    'Desarrollo Organización',
    'Desarrollo Personal',
    'Desarrollo Web',
    'Deseo De Aprender',
    'Deseos De Aprender',
    'Design Thinking',
    'Designbuilder',
    'Designer',
    'Destreza',
    'Deswik',
    'Detallista',
    'Determinación',
    'Determinada',
    'Dev C++',
    'Devc',
    'Devexpress',
    'Devicenet',
    'Devnet',
    'Devops',
    'Dexon',
    'Dharma',
    'Dharma Usaha',
    'Dhcp',
    'Dhtml',
    'Dia',
    'Dialux',
    'Diamino',
    'Dibujante',
    'Dibujo',
    'Dicom',
    'Digitación',
    'Digitador',
    'Digital Marketing',
    'DigSilent',
    'Diligencia',
    'Diligente',
    'Dimasof',
    'Dimasoft',
    'Dimensión',
    'Dimensions',
    'Dims',
    'Dinámico/a',
    'Dinamismo',
    'Dinesat',
    'Dips',
    'Dirac',
    'Dirección De Arte',
    'Dirección De Empresas',
    'Dirección De Equipos',
    'Dirección De Equipos De Trabajo',
    'Dirección De Personas',
    'Dirección De Proyectos',
    'Dirección Estratégica',
    'Director',
    'Disciplina',
    'Disciplinado/a',
    'Discover',
    'Discoverer',
    'Discovery',
    'Discreta',
    'Diseño',
    'Diseño 3D',
    'Diseño Arquitectónico',
    'Diseño De Procesos',
    'Diseño De Productos',
    'Diseño De Proyectos',
    'Diseño Digital',
    'Diseño Editorial',
    'Diseño Grafico',
    'Diseño Institucional',
    'Diseño Web',
    'Dispatch',
    'Disponer De Pensamiento Estratégico',
    'Disvet',
    'Divages',
    'Django',
    'Dmelect',
    'Dms',
    'Dnasp',
    'Dns',
    'Docencia',
    'Docencia Universitaria',
    'Docflow',
    'Docker',
    'Documentación',
    'Documentum',
    'Docured',
    'Docushare',
    'Docuware',
    'Dokeos',
    'Dolibarr',
    'Dominio De Inglés',
    'Dominio Del Idioma Inglés',
    'Dominio Del Inglés',
    'Domotica',
    'Doppler',
    'Dopsoft',
    'Dos',
    'Dotnetnuke',
    'Dotproject',
    'Draftsight',
    'Dragon Naturally Speaking',
    'Dreamweaver Cs3',
    'Dreamweaver Cs4',
    'Dreamweaver Cs5',
    'Dreamweaver Cs6',
    'Dreamweaver Mx',
    'Drive',
    'Drivers',
    'Drones',
    'Dropbox',
    'Drupal',
    'Drysoft',
    'Dspace',
    'Dts',
    'Dunga',
    'DVD Studio Pro',
    'Dwdm',
    'Dwsim',
    'Dyane',
    'Dynamic',
    'Dynamics',
    'Dynamics Ax',
    'Dynamo',
    'e-Commerce',
    'Eagle',
    'Ease',
    'Easyfit',
    'Easyplanex',
    'Eaudit',
    'Eclipse',
    'Eclipse Ide',
    'Ecodial',
    'Economática',
    'Economía',
    'Ecotech',
    'Ecotect',
    'Ecrm',
    'Ecuapass',
    'Edelfos',
    'Edem',
    'Edición',
    'Edición de video',
    'Edición Fotográfica',
    'Edicontabilidad',
    'Edig',
    'Edigraf',
    'Edigraph',
    'Edilim',
    'Edimatri',
    'Edimatrix',
    'Ediremuneraciones',
    'Editores',
    'Editores De Video',
    'Edius',
    'Edmodo',
    'Edsa',
    'Edulinux',
    'Ees',
    'Efectividad',
    'Eficacia',
    'Eficaz',
    'Eficiencia',
    'Eficiencia Energética',
    'Ehealth',
    'Ejb',
    'Elaboración De Informes',
    'Elaboración De Presupuestos',
    'Elasticsearch',
    'Elastix',
    'Elcad',
    'Elearning',
    'Elecdes',
    'Electricidad',
    'Electricidad Industrial',
    'Electronic Workbench',
    'Electrónica',
    'Electronics Workbench',
    'Elipse',
    'Elite',
    'Ellipse',
    'Elocuencia',
    'Elocuente',
    'Elypse',
    'Emaze',
    'Emerix',
    'Emonitor',
    'Empatía',
    'Empatica',
    'Empático',
    'Empower',
    'Emprendedor',
    'Emprendedora',
    'Emprendimiento',
    'Ems',
    'Emule',
    'En Equipo',
    'En Ventas',
    'Encarta',
    'Encase',
    'Encore',
    'EndNote',
    'Energía',
    'Energías Renovables',
    'Enérgica',
    'Energyplus',
    'Enervista',
    'Enfoque a Resultados',
    'Enfoque en Resultados',
    'Engage',
    'Eniac',
    'Enroute',
    'Enseñanza',
    'Enseñar',
    'Enternet',
    'Enterprise',
    'Enterprise Architect',
    'Entity Framework',
    'Entrevista Por Competencias',
    'Entrevistas',
    'Entrevistas Por Competencias',
    'Entusiasmo',
    'Entusiasta',
    'Envi',
    'Epanet',
    'Epanet 2.0',
    'Epcworks',
    'Epicenter',
    'Epicor',
    'Epidat',
    'Epidata',
    'Epiinfo',
    'Epiphany',
    'Eplan',
    'Eqdz',
    'Equifax',
    'Equitrac',
    'Er Mapper',
    'Erdas',
    'Ericsson',
    'Ermapper',
    'Eroom',
    'Erp',
    'Erp2',
    'Erwin',
    'Esac',
    'Escritura',
    'Escritura Creativa',
    'Escucha',
    'Escucha Activa',
    'Escuchar',
    'Esforzado/a',
    'Esi Tronic',
    'Espabiblio',
    'Español',
    'Espíritu Comercial',
    'Espíritu De Equipo',
    'Espíritu De Servicio',
    'Espíritu De Superación',
    'Esprit',
    'Essbase',
    'Estados Financieros',
    'Estratega',
    'Estrategia',
    'Estrategia Comercial',
    'Estrategia De Marketing',
    'Estrategia De Negocios',
    'Estrategia Digital',
    'Estrategia Empresarial',
    'Estrategias',
    'Estrategias De Marketing',
    'Estratégico/a',
    'Estraus',
    'Estudios De Mercado',
    'Etabs',
    'Etap',
    'Etaps',
    'Ethereal',
    'Ethernet',
    'Ethical Hacking',
    'Ethnograph',
    'Etl',
    'Etnograph',
    'Etruck',
    'Eucasim',
    'Euclid',
    'Eudora',
    'Eugcom',
    'Euromonitor',
    'Evaluación',
    'Evaluación De Desempeño',
    'Evaluación De Proyectos',
    'Evaluación De Riesgos',
    'Evaluación Psicológica',
    'Everest',
    'Evernote',
    'Eviews',
    'Evolution',
    'Exact',
    'Exacttarget',
    'Exactus',
    'Examine2d',
    'Excel 2003',
    'Excel 2007',
    'Excel 2010',
    'Excel 2013',
    'Excelencia',
    'Excelencia Operacional',
    'Excelente Atención Al Cliente',
    'Excelente Atención Al Público',
    'Excelente Capacidad De Liderazgo',
    'Excelente Comunicación',
    'Excelente Comunicación Interpersonal',
    'Excelente Comunicación Oral',
    'Excelente Dicción',
    'Excelente Disposición',
    'Excelente Manejo De Relaciones Interpersonales',
    'Excelente Ortografía',
    'Excelente Presencia',
    'Excelente Redacción',
    'Excelente Relaciones Interpersonales',
    'Excelente Trabajo en Equipo',
    'Excelente Trato',
    'Excelente Trato Con Clientes',
    'Excelentes Habilidades Comunicacionales',
    'Excelentes Habilidades Comunicativas',
    'Excelentes Habilidades Interpersonales',
    'Excelentes Relaciones Interpersonales',
    'Excelentes Relaciones Personales',
    'Excelso',
    'Exchange 2003',
    'Exchange 2010',
    'Exelearning',
    'Experfit',
    'Experiencia',
    'Experiencia en Atención Al Cliente',
    'Experiencia en Atención Al Público',
    'Experiencia en Manejo De Personal',
    'Experiencia en Trabajo en Equipo',
    'Experiencia en Ventas',
    'Expert',
    'Expert Choice',
    'Expertfit',
    'Expresión Escrita',
    'Expresión Oral',
    'Express',
    'Extend',
    'Extendsim',
    'Extjs',
    'Extranet',
    'Extreme',
    'Extrovertida',
    'Ezrez',
    'Facebook',
    'Facebook Ads',
    'Facele',
    'Fácil Adaptación',
    'Fácil Adaptación a Los Cambios',
    'Fácil Aprendizaje',
    'Facilidad Aprendizaje',
    'Facilidad De Adaptación',
    'Facilidad De Aprendizaje',
    'Facilidad De Comunicación',
    'Facilidad De Expresión',
    'Facilidad De Expresión Oral',
    'Facilidad De Palabra',
    'Facilidad De Trabajo en Equipo',
    'Facilidad Para Aprender',
    'Facilidad Para El Trabajo en Equipo',
    'Facilidad Para Establecer Relaciones Interpersonal',
    'Facilidad Para La Comunicación',
    'Facilidad Para Trabajar Bajo Presión',
    'Facilidad Para Trabajar en Equipo',
    'Facilidad Para Trabajar en Grupo',
    'Facilitador',
    'Factiva',
    'Factorytalk',
    'Factset',
    'Facturación',
    'Facturación electrónica',
    'Facturacion.cl',
    'Facturaplus',
    'Factusol',
    'Falanet',
    'Fanuc',
    'Farmcontrol',
    'Fastcam',
    'Faster',
    'Fasterbook',
    'Fathom',
    'Fecusa',
    'Fedora',
    'Feflow',
    'Femap',
    'Femlab',
    'Fenix',
    'Festo',
    'Fexline',
    'Fiabilidad',
    'Fiable',
    'Fibra Óptica',
    'Ficharayen',
    'Fidelio',
    'Fidelius',
    'Fidelización De Clientes',
    'Fidelizador',
    'Fidens',
    'Figaro',
    'Figma',
    'Filefinder',
    'Filemaker',
    'Filemaker Pro',
    'Filenet',
    'Filezilla',
    'Filmora',
    'Fin 100',
    'Fin 700',
    'Final Cut',
    'Final Cut Pro',
    'Final Cut Pro 7',
    'Final Cut Pro x',
    'Final Cut Studio',
    'Final Draft',
    'Finale',
    'Financial',
    'Financials',
    'Finanzas',
    'Finanzas Corporativas',
    'Finesse',
    'Finex',
    'Firebird',
    'Firefox',
    'Firewall',
    'Fisa',
    'Fishtalk',
    'FL Studio',
    'Flac',
    'Flac3d',
    'Flamingo',
    'Flash Cs3',
    'Flash Cs4',
    'Flash Cs5',
    'Flash Mx',
    'Flex',
    'Flex Line',
    'Flex Win',
    'Flexcon',
    'Flexcube',
    'Flexibilidad',
    'Flexibilidad Adaptabilidad',
    'Flexibilidad Al Cambio',
    'Flexibilidad Cognitiva',
    'Flexibilidad Horaria',
    'Flexibilidad y capacidad de adaptación',
    'Flexible',
    'Flexisign',
    'Flexline',
    'Flexsim',
    'Flexwin',
    'Flickr',
    'Florence',
    'Flow',
    'Flowcharting',
    'Flowcode',
    'Flowjo',
    'Flowmaster',
    'Fluent',
    'Fluidsim',
    'Fluke',
    'Foco en El Cliente',
    'Foco en Resultados',
    'Focus',
    'Fomplus',
    'Fonasa',
    'Fonendo',
    'Fontana',
    'Fontlab',
    'Fontographer',
    'Food Processor',
    'Foodwise',
    'Foran',
    'Forestruck',
    'Formación De Equipos',
    'Formación De Equipos De Trabajo',
    'Formador De Equipos',
    'Formador De Equipos De Trabajo',
    'Formato Marc',
    'Forms',
    'Formulación',
    'Formulación De Proyectos',
    'Formz',
    'Fortigate',
    'Fortinet',
    'Fortran',
    'Fortune',
    'Forward',
    'Fotografía',
    'Fotografía Digital',
    'Fotografía Profesional',
    'Fotógrafo',
    'Foxbase',
    'Foxboro',
    'Foxpro',
    'Fpga',
    'Fracttal',
    'Framework',
    'Francés',
    'Francés Básico',
    'Freebsd',
    'Freecad',
    'Freehand 10',
    'Freehand Mx',
    'Freemind',
    'Freeship',
    'Freightsoft',
    'Front',
    'Front Page',
    'Frontend',
    'Frontier',
    'Frontsuite',
    'Fruity Loops',
    'Ftp',
    'Fugit',
    'Fullpyme',
    'Fullstar',
    'Fusion',
    'Fútbol',
    'Gabriel',
    'Galac',
    'Galileo',
    'Gambit',
    'Gams',
    'Gamx',
    'Ganas De Aprender',
    'Ganas De Crecer',
    'Ganas De Trabajar',
    'Gandia',
    'Gantt',
    'Ganttproject',
    'Garage Band',
    'Garra',
    'Garzón',
    'Garzona',
    'Gasfiteria',
    'Gasper',
    'Gastronomía',
    'Gauss',
    'Gaussian',
    'Gcdkit',
    'Gds',
    'Gdsis',
    'Gemcom',
    'Gems',
    'Geneious',
    'Genera',
    'Generación De Contenidos',
    'Generación De Ideas e Innovación',
    'Génesis',
    'Genesix',
    'Genesys',
    'Genetec',
    'Genex Assistant',
    'Genex Probe',
    'Genexus',
    'Genomi',
    'Genopro',
    'Geoda',
    'Geoframe',
    'Geogebra',
    'Geogenius',
    'Geographix',
    'Geolog',
    'Geología',
    'Geomagic',
    'Geomedia',
    'Geometra',
    'Geomos',
    'Geopos',
    'Geopsy',
    'Geoserver',
    'Geoslope',
    'Geosoft',
    'Geostru',
    'Geostudio',
    'Geotecnia',
    'Geovictoria',
    'Gephi',
    'Gerencia',
    'Gerencia De Proyectos',
    'Gerenciamiento De Proyectos',
    'Gesaba',
    'Gesad',
    'Gesam',
    'Gescom',
    'Gescon',
    'Geshotel',
    'Gesper',
    'Gespyme',
    'Gestión',
    'Gestión Académica',
    'Gestión Administrativa',
    'Gestión Ambiental',
    'Gestión Comercial',
    'Gestión Cultural',
    'Gestión De Activos',
    'Gestión De Calidad',
    'Gestión De Cambios',
    'Gestión De Clientes',
    'Gestión De Compras',
    'Gestión De Contratos',
    'Gestión De Cuentas',
    'Gestión De Equipos',
    'Gestión De Equipos De Trabajo',
    'Gestión De Inventarios',
    'Gestión De La Información',
    'Gestión De La Innovación',
    'Gestión De Mantenimiento',
    'Gestión De Operaciones',
    'Gestión De Personas',
    'Gestión De Prensa',
    'Gestión De Presupuestos',
    'Gestión De Procesos',
    'Gestión De Productos',
    'Gestión De Proveedores',
    'Gestión De Proyectos',
    'Gestión De Recursos Humanos',
    'Gestión De Redes Sociales',
    'Gestión De Ventas',
    'Gestión Del Cambio',
    'Gestión Del Tiempo',
    'Gestión Empresarial',
    'Gestión Estratégica',
    'Gestión Financiera',
    'Gestión Organización',
    'Gestor',
    'Gestper',
    'Gestpyme',
    'Gfi Languard',
    'Ghost',
    'Gicona',
    'Gif Animator',
    'Gimp',
    'Gis',
    'Git',
    'Github',
    'Gitlab',
    'Glassfish',
    'Global',
    'Globe',
    'Glpi',
    'Gmail',
    'Gmwin',
    'Gns3',
    'Gnu Linux',
    'Gnumeric',
    'Gnuplot',
    'Goal Bus',
    'Goldmine',
    'Goldsim',
    'Goldwave',
    'Golive',
    'Google Ads',
    'Google Adwords',
    'Google Analytics',
    'Google Apps',
    'Google Chrome',
    'Google Docs',
    'Google Drive',
    'Google Earth',
    'Google Earth Pro',
    'Gosocket',
    'Gourmet',
    'Gournet',
    'Gproms',
    'Gps',
    'Grafos',
    'Grails',
    'Gran Capacidad Analítica',
    'Gran Capacidad De Adaptación',
    'Gran Capacidad De Análisis',
    'Gran Capacidad De Aprendizaje',
    'Gran Capacidad De Liderazgo',
    'Gran Capacidad De Organización',
    'Gran Capacidad De Trabajo Bajo Presión',
    'Gran Capacidad De Trabajo en Equipo',
    'Grapher',
    'Graphisoft Archicad',
    'Graphmatica',
    'Graphpad',
    'Graphpad Prism',
    'Grass',
    'Grasshopper',
    'Great Plains',
    'Greenstone',
    'Gretl',
    'Groove',
    'Groovy',
    'Groundwater Vistas',
    'Groupwise',
    'Gsap',
    'Gslib',
    'Gslope',
    'Gsm',
    'Gsuite',
    'Gtstrudl',
    'Guardia',
    'Guardia De Seguridad',
    'Guestware',
    'Gurobi',
    'Gvmapper',
    'Gvsig',
    'h Canales',
    'Hábil',
    'Habilidad Analítica',
    'Habilidad Computacional',
    'Habilidad Comunicacional',
    'Habilidad Comunicativa',
    'Habilidad De Aprender Rápido',
    'Habilidad De Comunicación',
    'Habilidad De Liderazgo',
    'Habilidad De Negociación',
    'Habilidad De Trabajar Bajo Presión',
    'Habilidad De Trabajo en Equipo',
    'Habilidad en Ventas',
    'Habilidad Numérica',
    'Habilidad Para Aprender',
    'Habilidad Para El Trabajo en Equipo',
    'Habilidad Para La Toma De Decisiones',
    'Habilidad Para Resolver Problemas',
    'Habilidad Para Tomar Decisiones',
    'Habilidad Para Trabajar Bajo Presión',
    'Habilidad Para Trabajar en Equipo',
    'Habilidad Social',
    'Habilidades Administrativas',
    'Habilidades Analíticas',
    'Habilidades Blandas',
    'Habilidades Blandas Desarrolladas',
    'Habilidades Comerciales',
    'Habilidades Computacionales',
    'Habilidades Comunicacionales',
    'Habilidades Comunicativas',
    'Habilidades Comunicativas Desarrolladas',
    'Habilidades De Comunicación',
    'Habilidades De Liderazgo',
    'Habilidades De Negociación',
    'Habilidades De Trabajo en Equipo',
    'Habilidades Directivas',
    'Habilidades en Ventas',
    'Habilidades Interpersonales',
    'Habilidades Interpersonales De Comunicación',
    'Habilidades Manuales',
    'Habilidades Matemáticas',
    'Habilidades Numéricas',
    'Habilidades Organizativas',
    'Habilidades Para Trabajar en Equipo',
    'Habilidades Para Trabajo en Equipo',
    'Habilidades Sociales',
    'Habilidades Técnicas',
    'Hablar en Público',
    'Haccp',
    'Hacha',
    'Hadoop',
    'Hammer',
    'Hard Dollar',
    'Harvest',
    'Hasar',
    'Haskell',
    'Hcanales',
    'Hdm 4',
    'Hec Hms',
    'HEC-RAS',
    'Helas',
    'Helisa',
    'Help Desk',
    'Hematos',
    'Hermes',
    'Herramientas Case',
    'Herramientas de Desarrollo',
    'Herramientas de Diseño',
    'Herramientas Gráficas',
    'Hextran',
    'Hfm',
    'Hibernate',
    'Hidráulica',
    'Highjump',
    'Hikvision',
    'Hiper Renta',
    'Hirens Boot',
    'Hive',
    'Hmi',
    'Hojas de Cálculo',
    'Holistor',
    'Homer',
    'Honestidad',
    'Honestidad e Integridad',
    'Honesto/a',
    'Honeywell',
    'Honradez',
    'Honrado/a',
    'Hootsuite',
    'Horizon',
    'Horizonte',
    'Hormigon 318',
    'Horus',
    'Hospes',
    'Host',
    'Hostelsystem',
    'Hosting',
    'Hot Potatoes',
    'Hotel New',
    'Hotelnew',
    'Hotelogix',
    'Hotelware',
    'Hotmail',
    'HP Service Manager',
    'Hp-Ux',
    'Hplc',
    'Hsc',
    'Html',
    'Html5',
    'Htri',
    'Http',
    'Huawei',
    'Hubspot',
    'Human Force',
    'Humano 2',
    'Humildad',
    'Humilde',
    'Hummingbird',
    'Hydrus',
    'Hypack',
    'Hyper-V',
    'Hyperion',
    'Hyperrenta',
    'Hypershot',
    'Hyperterminal',
    'Hysys',
    'Ibatis',
    'Iber',
    'Ibm',
    'Ibs',
    'Ibwave',
    'Icdl',
    'Icefaces',
    'Icon',
    'Iconstruye',
    'Icontador',
    'Ics',
    'Idea',
    'Ideas',
    'Idempiere',
    'Idiomas',
    'Idrisi',
    'Ifix',
    'Ifrs',
    'Igpet',
    'Igrafx',
    'Iis',
    'Ilias',
    'Ilife',
    'Illustrator Cc',
    'Illustrator Cs',
    'Illustrator Cs3',
    'Illustrator Cs4',
    'Illustrator Cs5',
    'Illustrator Cs6',
    'Ilustración',
    'Ilustración Digital',
    'Ilwis',
    'Imagej',
    'Imageready',
    'Imagestion',
    'Imageware',
    'Imaging',
    'Imed',
    'Imovie',
    'Impact',
    'Impacto e Influencia',
    'Impax',
    'Impera',
    'Importaciones',
    'Impresión 3D',
    'Impuestos',
    'Impulse',
    'In Touch',
    'Inbound Marketing',
    'Inconcert',
    'Incopy',
    'Independiente',
    'Indesign Cs3',
    'Indesign Cs5',
    'Indesign Cs6',
    'Indexa',
    'Indicadores De Gestión',
    'Indigo',
    'Inet',
    'Inews',
    'Infact',
    'Infhotel',
    'Infilink',
    'Infinity',
    'Infoauto',
    'Infocent',
    'Infocomex',
    'Infolab',
    'Infoland',
    'Infolder',
    'Infomaker',
    'Infopath',
    'Infor',
    'Infoream',
    'Inforest',
    'Informat',
    'Informix',
    'Inforpyme',
    'Infostat',
    'Infosys',
    'Infotrans',
    'Infoworks',
    'Infraestructura',
    'Infragistics',
    'Infraworks',
    'Ingel',
    'Ingeniería',
    'Ingeniería Civil',
    'Ingeniería De Procesos',
    'Ingeniería De Proyectos',
    'Ingeniero en Prevención De Riesgos',
    'Ingenioso(a)',
    'Ingeval',
    'Ingres',
    'Inhova',
    'Iniciativa',
    'Iniciativa e Innovación',
    'Iniciativa Propia',
    'Inkscape',
    'Innova',
    'Innovación',
    'Innovador',
    'Innovadora',
    'Innsist',
    'Inplant',
    'Inpower',
    'Inroads',
    'Insico',
    'Inside',
    'Insight',
    'Insite',
    'Inspección Técnica De Obras',
    'Instagram',
    'Installshield',
    'Instapage',
    'Instoreview',
    'Instrucalc',
    'Instrumentación',
    'Instrumentación Industrial',
    'Insul',
    'Integra',
    'Integración',
    'Integral',
    'Integridad',
    'Intel',
    'Intelicad',
    'Inteligencia',
    'Inteligencia Artificial',
    'Inteligencia De Negocios',
    'Inteligencia Emocional',
    'Inteligencia Empresarial',
    'Inteligencia Social',
    'Inteligente',
    'Intelisis',
    'Intellect',
    'Intellicad',
    'Intellij',
    'Intellimine',
    'Interact',
    'Interactive',
    'Interbase',
    'Interés Por Aprender',
    'Internetworking',
    'Interpretación De Planos',
    'Intertrace',
    'Intools',
    'Intouch',
    'Intraway',
    'Inttra',
    'Inventarios',
    'Inventor',
    'Inventor Autodesk',
    'Inventor Professional',
    'Invertor',
    'Investigación',
    'Investigación Cualitativa',
    'Investigación De Mercados',
    'Investigación Jurídica',
    'Investigador',
    'Invision',
    'Invop',
    'Iogas',
    'Ion Setup',
    'Ionic',
    'Ios',
    'Ip3',
    'Ipad',
    'Ipcop',
    'Iphone',
    'Iphoto',
    'Ipi2win',
    'Ipsos',
    'Iptables',
    'Iraf',
    'Ireport',
    'Irfanview',
    'Iris',
    'Irislab',
    'Ironport',
    'Irrimax',
    'Irs',
    'Isatis',
    'Isc3',
    'Iscala',
    'Iscst3',
    'Iseries',
    'Isidora',
    'Isis',
    'ISO 9001',
    'Iso27001',
    'Isoeasy',
    'Isokey',
    'Isonet',
    'Isosystem',
    'Isotools',
    'Isplus',
    'Ispol',
    'Ispsoft',
    'Istqb',
    'Istram',
    'Italiano',
    'Itemizar',
    'Ithink',
    'Itil',
    'Itunes',
    'Ivr',
    'Iwork',
    'J2ee',
    'J2me',
    'J2se',
    'Janium',
    'Jasperreports',
    'Jaspersoft',
    'Java',
    'Java Ee',
    'Java J2ee',
    'Java J2se',
    'Java2ee',
    'Javafx',
    'Javascript',
    'Jaws',
    'Jboss',
    'Jbpm',
    'Jbuilder',
    'Jcl',
    'Jclic',
    'Jcreator',
    'Jd Edwards',
    'Jd Edwards Enterpriseone',
    'Jda',
    'Jde',
    'Jdedwars',
    'Jdeveloper',
    'Jedox',
    'Jee',
    'Jenkins',
    'Jigsaw',
    'Jira',
    'Jk Bench',
    'Jk Simblast',
    'Jk Simmet',
    'Jkbench',
    'Jksimblast',
    'Jksimfloat',
    'Jksimmet',
    'Jmeter',
    'Jmetrik',
    'Jmineops',
    'Jmp',
    'Joomla',
    'Journal',
    'Jpa',
    'Jquery',
    'Jquery Mobile',
    'Jqueryui',
    'Js',
    'Jsf',
    'Json',
    'Jsp',
    'Julia',
    'Jump',
    'Juniper',
    'Junit',
    'Justtime',
    'Kahoot',
    'Kaizen',
    'Kaledo',
    'Kaledo Style',
    'Kanban',
    'Kardex',
    'Kaspersky',
    'Kastor',
    'Kepserver',
    'Kepserverex',
    'Kerkythea',
    'Kernmic',
    'Kettle',
    'Keynote',
    'Keyshot',
    'Kicad',
    'Kinovea',
    'Kitchendraw',
    'Kiu',
    'Kiwiplan',
    'Knime',
    'Koha',
    'Kompozer',
    'Komtrax',
    'Kopland',
    'Kosmo',
    'Kpi',
    'Kronos',
    'Kubernetes',
    'Kupay',
    'La Capacidad De Tomar Decisiones',
    'Labcore',
    'Laboratorio',
    'Labview',
    'Ladder',
    'Lamp',
    'Land',
    'Landesk',
    'Landmark',
    'Lanix',
    'Lanmark',
    'Lantek',
    'Laravel',
    'Larrondo',
    'Latex',
    'Laudus',
    'Lawson',
    'Layla',
    'Layout',
    'Ldap',
    'Leadership',
    'Leal',
    'Lealtad',
    'Lean',
    'Lean Management',
    'Lean Manufacturing',
    'Lean Six Sigma',
    'Leapfrog',
    'Leasesoft',
    'Leasoft',
    'Lectra',
    'Lectura De Planos',
    'Lectura e Interpretación De Planos',
    'Lectura e Interpretación De Planos Eléctricos',
    'Legacy',
    'Legal Publishing',
    'Legato',
    'Legislación Laboral',
    'Lekin',
    'Lemontech',
    'Lengua De Señas',
    'Lengua De Señas Nivel Básico',
    'Lenguajes de programación',
    'Leopard',
    'Lepton',
    'less',
    'Levantamiento De Procesos',
    'Lexia',
    'Lexis Nexis',
    'Libreoffice',
    'Licencia Clase b',
    'Licencia Clase d',
    'Licencia De Conducir',
    'Licitaciones',
    'Lidar',
    'Líder',
    'Líder De Equipos',
    'Líder Positivo',
    'Liderar',
    'Liderar Equipos',
    'Liderar Equipos De Trabajo',
    'Liderar Grupos De Trabajo',
    'Liderazgo',
    'Liderazgo Colaborativo',
    'Liderazgo De Equipos',
    'Liderazgo De Equipos De Trabajo',
    'Liderazgo De Equipos Multidisciplinarios',
    'Liderazgo De Proyectos',
    'Liderazgo Efectivo',
    'Liderazgo Participativo',
    'Liderazgo Positivo',
    'Liderazgo Situacional',
    'Liderazgo Transformacional',
    'Liferay',
    'Liggghts',
    'Lightscape',
    'Lightwave',
    'Limdep',
    'Limesurvey',
    'Limpieza',
    'Lims',
    'Lince',
    'Lindo',
    'Lingo',
    'Link',
    'Linkedin',
    'Linkone',
    'Linq',
    'Linux',
    'Liquid',
    'Lisa',
    'Liscad',
    'Lisp',
    'Lisrel',
    'Litigación',
    'Livelink',
    'Livetype',
    'Livewire',
    'Load Runner',
    'Locución',
    'Logam',
    'Logfire',
    'Loggernet',
    'Logic',
    'Logic Pro',
    'Logic Pro x',
    'Logicat',
    'Logis',
    'Logística',
    'Logitrace',
    'Logixpro',
    'Logmein',
    'Logo',
    'Logosoft',
    'Logplot',
    'Logro De Metas',
    'Logro De Objetivos',
    'Logware',
    'Lombardi',
    'Lotus',
    'Lotus 123',
    'Lotus Domino',
    'Lotus Notes',
    'Loyal',
    'Lte',
    'Ltspice',
    'Lulowin',
    'Lumenlux',
    'Lumion',
    'M2000',
    'Mach3',
    'Machine Learning',
    'Macola',
    'MacOS',
    'MacOS X',
    'Macromedia Director',
    'Macromedia Flash',
    'Macromedia Flash 8',
    'Macromedia Flash Mx',
    'Macromedia Freehand Mx',
    'Macromedia Mx',
    'Macromedia Studio',
    'Macromedia Studio Mx',
    'Macros',
    'Macrostation',
    'Madio',
    'Madlab',
    'Maestro',
    'Magaya',
    'Magento',
    'Magic',
    'Magicdraw',
    'Magix',
    'Magma',
    'Magnitude',
    'Magnus',
    'Mail',
    'Mailchimp',
    'Mainframe',
    'Maintenix',
    'Maintraq',
    'Maintscape',
    'Mambo',
    'Management',
    'Manejo',
    'Manejo Avanzado Del Idioma Inglés',
    'Manejo Computacional',
    'Manejo Computacional Avanzado',
    'Manejo Computacional Nivel Usuario',
    'Manejo Comunicacional',
    'Manejo De Atención Al Cliente',
    'Manejo De Base De Datos',
    'Manejo De Caja',
    'Manejo De Cartera De Clientes',
    'Manejo De Clientes',
    'Manejo De Computadoras',
    'Manejo De Conflictos',
    'Manejo De Crisis',
    'Manejo De Crm',
    'Manejo De Datos',
    'Manejo De Dinero',
    'Manejo De Emociones',
    'Manejo De Equipo De Trabajo',
    'Manejo De Equipos Multidisciplinarios',
    'Manejo De Erp',
    'Manejo De Estrés',
    'Manejo De Grupos',
    'Manejo De Grupos De Trabajo',
    'Manejo De Habilidades Blandas',
    'Manejo De Herramientas',
    'Manejo De Herramientas Computacionales',
    'Manejo De Herramientas Digitales',
    'Manejo De Herramientas Informáticas',
    'Manejo De Idiomas',
    'Manejo De Indicadores De Gestión',
    'Manejo De Inglés',
    'Manejo De Inglés Básico',
    'Manejo De Inglés Intermedio',
    'Manejo De Inventarios',
    'Manejo De La Frustración',
    'Manejo De Objeciones',
    'Manejo De Pc',
    'Manejo De Pc Nivel Usuario',
    'Manejo De Personal',
    'Manejo De Personal a Cargo',
    'Manejo De Presupuestos',
    'Manejo De Problemas',
    'Manejo De Programas Computacionales',
    'Manejo De Proveedores',
    'Manejo De Proyectos',
    'Manejo De Público',
    'Manejo De Redes Sociales',
    'Manejo De Relaciones Interpersonales',
    'Manejo De Rrss',
    'Manejo De Sistemas',
    'Manejo De Sistemas Administrativos',
    'Manejo De Sistemas Operativos',
    'Manejo De Situaciones',
    'Manejo De Softwares',
    'Manejo De Tensiones',
    'Manejo De Tics',
    'Manejo De Trabajo Bajo Presión',
    'Manejo Del Estrés',
    'Manejo Del Idioma Inglés',
    'Manejo Del Tiempo',
    'Manejo Grupal',
    'Manhattan',
    'Manicurista',
    'Manipulación De Alimentos',
    'Mantec',
    'Mantención',
    'Mantenimiento',
    'Mantenimiento Industrial',
    'Mantenimiento Preventivo',
    'Mantis',
    'Manuales',
    'Manualidades',
    'Manugistic',
    'Map3d',
    'Mapics',
    'Mapinfo',
    'Mapit',
    'Maple',
    'Mapmaker',
    'Maprex',
    'Mapscenes',
    'Mapserver',
    'Mapsource',
    'Maptek Vulcan',
    'Maquillador',
    'Maquillador Profesional',
    'Maquillaje',
    'Marel',
    'Margin Minder',
    'Mariadb',
    'Marketing',
    'Marketing Digital',
    'Marketing Estratégico',
    'Markstrat',
    'Marsha',
    'Marvel',
    'Mascont',
    'Maskana',
    'Maso Terapeuta',
    'Masremu',
    'Master',
    'Masterbase',
    'Mastercam',
    'Mastergen',
    'Masterkey',
    'Mastermind',
    'Mastersoft',
    'Matemáticas',
    'Mateonet',
    'Materialize',
    'Mathcad',
    'Mathcad 14',
    'Mathematica',
    'Mathtype',
    'Matlab',
    'Matman',
    'Matpower',
    'Matrix',
    'Maven',
    'Maxent',
    'Maxima',
    'Maximise',
    'Maxirest',
    'Maxlite',
    'Maxqda',
    'Maxsurf',
    'Maxwell',
    'Maya',
    'Maya 3d',
    'Mcafee',
    'Mdaemon',
    'Mdsolids',
    'Mdt',
    'Me Adapto a Los Cambios',
    'Me Gusta Aprender',
    'Me Gusta Aprender Cosas Nuevas',
    'Me Gusta El Trabajo en Equipo',
    'Me Gusta Trabajar',
    'Me Gusta Trabajar en Equipo',
    'Mecánica Automotriz',
    'Mecánico Automotriz',
    'Mecánico/a',
    'Mechanical',
    'Mechanical Desktop',
    'Mediamind',
    'Medic',
    'Medii',
    'Medilink',
    'Medio Ambiente',
    'Medios Digitales',
    'Medios Sociales',
    'Medisyn',
    'Medisyn 3.0',
    'Medlab Qc',
    'Meduc',
    'Mega',
    'Megasuite',
    'Megasystem',
    'Megatime',
    'Megatrack',
    'Mejora Continua',
    'Mejora De Procesos',
    'Mejoramiento Continuo',
    'Melita',
    'Memoq',
    'Memory',
    'Memsource',
    'Mencons',
    'Mendeley',
    'Menfis',
    'Menu Andes',
    'Mercado Público',
    'Mercatus',
    'Merchandising',
    'Mercurial',
    'Mercury',
    'Meribia',
    'Meridian',
    'Meridium',
    'Merlin',
    'Mesap',
    'Message Broker',
    'Messenger',
    'Mestrec',
    'Mestrenova',
    'Meta 4',
    'Meta Stock',
    'Meta Trader 4',
    'Meta4',
    'Metasploit',
    'Metastock',
    'Metatrader',
    'Meteonorm',
    'Methasys',
    'Methodo',
    'Meticulosidad',
    'Meticuloso/a',
    'Metódica',
    'Metodologías Ágiles',
    'Metra',
    'Metrics',
    'Metsim',
    'Mfg',
    'Mfgpro',
    'Micmac',
    'Miconserje',
    'Micro',
    'Microbiología',
    'Microcap',
    'Microcat',
    'Microcontroladores',
    'Microisis',
    'Microkey',
    'Micrologix',
    'Micromine',
    'Micros',
    'Microservicios',
    'Microsiga',
    'Microsip',
    'Microsoft 2007',
    'Microsoft 2010',
    'Microsoft 98',
    'Microsoft Access',
    'Microsoft Dynamics Crm',
    'Microsoft Excel',
    'Microsoft Exchange',
    'Microsoft Office',
    'Microsoft Project',
    'Microsoft SQL Server',
    'Microsoft Teams',
    'Microsoft Word',
    'Microsoft Xp',
    'Micross',
    'Microstation',
    'Microstrategy',
    'Microsystem',
    'Microtrap',
    'Microwin',
    'Midas',
    'Middleware',
    'Mike 21',
    'Mikroc',
    'Mikrotik',
    'Milenio',
    'Millenium',
    'Millennium',
    'Mims',
    'Mincom',
    'Mindjet',
    'Mindmanager',
    'Minecare',
    'Minehaul',
    'Mineops',
    'Mineplan',
    'Minería',
    'Minerva',
    'Minesched',
    'Minesight',
    'Minesigth',
    'Minestar',
    'Minex',
    'Mini Tab',
    'Minicad',
    'Minicont',
    'Miniremu',
    'Minisoft',
    'Minitab',
    'Minitab 15',
    'Mins',
    'Mintab',
    'Minuciosa',
    'Miradi',
    'Mitsubishi',
    'Mixnet',
    'Mobile',
    'Mockshop',
    'Modaris',
    'Modbus',
    'Modelado 3d',
    'Modelamiento de datos',
    'Modeler',
    'Modellus',
    'Modflow',
    'Modsim',
    'Modsoft',
    'Modul8',
    'Modulab',
    'Moebius',
    'Moldeamiento De Procesos',
    'Moldflow',
    'Molinstec',
    'Molycop Tools',
    'Monarch',
    'Money',
    'Mongodb',
    'Monica',
    'Moodle',
    'Mootools',
    'Morningstar',
    'Mosaic',
    'Mosaix',
    'Motion',
    'Motion Graphics',
    'Motivación',
    'Motivación Al Logro',
    'Motivación De Equipos',
    'Motivación Por El Logro',
    'Motivado/a',
    'Motivador',
    'Motivadora',
    'Motorola',
    'Movex',
    'Movics',
    'Moviemaker',
    'Mozilla',
    'Mozilla Firefox',
    'Mp Software',
    'Mp2',
    'Mp9',
    'Mplab',
    'Mpls',
    'Mplus',
    'Mqseries',
    'Mr Comanda',
    'Mrp',
    'Ms Dos',
    'Msn',
    'Mta 9',
    'Muad Dib',
    'Muaddib',
    'Mudbox',
    'Multidisciplinario',
    'Multifuncional',
    'Multimedia',
    'Multisim',
    'Multitasking',
    'Multiterm',
    'Murex',
    'Muse',
    'Music Match',
    'Música',
    'Muy Buenas Relaciones Interpersonales',
    'Muy Responsable',
    'Mvc',
    'Mybatis',
    'Myeclipse',
    'Myob',
    'Mysap',
    'Mysql',
    'Mysql Workbench',
    'Nacar',
    'Nagios',
    'Napsis',
    'Nastran',
    'Natural',
    'Navicat',
    'Navigator',
    'Navis',
    'Navision',
    'Navisworks',
    'Navition',
    'Ncr',
    'Ncr3000',
    'Negociación',
    'Negociación Con Proveedores',
    'Negociación Efectiva',
    'Nemo',
    'Nemoceph',
    'Neo4j',
    'Neobook',
    'Neodata',
    'Neotel',
    'Neotur',
    'Neplan',
    'Nero',
    'Nessus',
    'Net',
    'Netact',
    'Netapp',
    'Netbackup',
    'Netbeans',
    'Netbook',
    'Netcar',
    'Netcont',
    'Netlogo',
    'Netmeeting',
    'Netnumen',
    'Netoffice',
    'Netsalud',
    'Netscape',
    'Netsuite',
    'Netsupport',
    'Netterm',
    'Netweaver',
    'Network',
    'Networker',
    'Networking',
    'Netx360',
    'New Hotel',
    'Nextiva',
    'Nexus',
    'Nginx',
    'Nhibernate',
    'Nice',
    'Nielsen',
    'Nivel Avanzado De Inglés',
    'Nivel Computacional Avanzado',
    'Nivel De Inglés Avanzado',
    'Nivel De Inglés Intermedio',
    'Nivel Intermedio De Inglés',
    'Nmap',
    'Nod32',
    'Node',
    'Nodejs',
    'Nodum',
    'Nokia',
    'Nominaplus',
    'Nomipaq',
    'Normas Iso',
    'Nortel',
    'Norton',
    'Norton Ghost',
    'Nosql',
    'Notebook',
    'Notepad',
    'Notes',
    'Novapoint',
    'Novasoft',
    'Novasys',
    'Novaxion',
    'Novell',
    'Novohit',
    'Npv Scheduler',
    'Nqdi',
    'Nsga',
    'Nubix',
    'Nubox',
    'Nudist',
    'Nuendo',
    'Null',
    'Numbers',
    'Nvivo',
    'Oasis',
    'Obiee',
    'Objetiva',
    'Observador',
    'Observadora',
    'Octave',
    'Odbc',
    'Odbms',
    'Odoo',
    'Office 2000',
    'Office 2003',
    'Office 2013',
    'Office 2016',
    'Office 365',
    'Office 97',
    'Office 98',
    'Office2007',
    'Office365',
    'Officebanking',
    'Officer',
    'Ofimática Avanzada',
    'Ofismart',
    'Olap',
    'Olidata',
    'Omega',
    'Omegat',
    'Omi',
    'Omicron',
    'Omnicast',
    'Omnigraffle',
    'Omnipage',
    'Omniplan',
    'Omniture',
    'Onbase',
    'Ondac',
    'Ondemand',
    'Onenote',
    'Oneworld',
    'Onyx',
    'Open',
    'Openbiblio',
    'Openbravo',
    'Openbsd',
    'Opencart',
    'Opencv',
    'Openerp',
    'Openfoam',
    'Opengl',
    'Openoffice',
    'Openproj',
    'Opensees',
    'Opensite',
    'Openstack',
    'Openvms',
    'Openworks',
    'Operaciones',
    'Operador',
    'Operador De Grúa Horquilla',
    'Operador De Maquinaria Pesada',
    'Operador Grúa Horquilla',
    'Operador Maquinaria Pesada',
    'Operario',
    'Opl',
    'Opmanager',
    'Opplusis',
    'Opticort',
    'Optimismo',
    'Optimista',
    'Optimización',
    'Optimización De Procesos',
    'Optimización Del Tiempo',
    'Optimus',
    'Optitex',
    'Optivision',
    'Opto 22',
    'Opus',
    'Oracle',
    'Oracle 10g',
    'Oracle 11g',
    'Oracle 8i',
    'Oracle 9i',
    'Oracle Data Integrator',
    'Oracle Database',
    'Oracle Developer',
    'Oracle Discoverer',
    'Oracle Ebs',
    'Oracle Financial',
    'Oracle Forms',
    'Oracle Hyperion',
    'Oracle Pl/Sql',
    'Oracle R12',
    'Oracle Service Bus',
    'Oracle Sql',
    'Oracle Sql Developer',
    'Orange',
    'Oratoria',
    'Orbis',
    'Orcad',
    'Ordenado/a',
    'Organización',
    'Organización De Eventos',
    'Organización De Trabajo',
    'Organización Del Trabajo',
    'Organización en El Trabajo',
    'Organización y Planificación',
    'Organizado/a',
    'Organizar',
    'Orientación a Clientes',
    'Orientación a La Calidad',
    'Orientación a La Eficiencia',
    'Orientación a La Excelencia',
    'Orientación a La Tarea',
    'Orientación a Las Personas',
    'Orientación a Los Objetivos',
    'Orientación a Los Resultados',
    'Orientación a Objetivos',
    'Orientación Al Cambio',
    'Orientación Al Cliente',
    'Orientación Al Cliente Interno',
    'Orientación Al Cumplimiento De Metas',
    'Orientación Al Cumplimiento De Objetivos',
    'Orientación Al Detalle',
    'Orientación Al Logro',
    'Orientación Al Logro De Metas',
    'Orientación Al Logro De Objetivos',
    'Orientación Al Resultado',
    'Orientación Al Servicio',
    'Orientación Al Trabajo en Equipo',
    'Orientación Al Usuario',
    'Orientación De Servicio',
    'Orientación De Servicio Al Cliente',
    'Orientación Estratégica',
    'Orientada a Objetivos',
    'Orientada a Resultados',
    'Orientada Al Logro',
    'Orientada Al Logro De Objetivos',
    'Orientada Al Trabajo en Equipo',
    'Orientado a Los Resultados',
    'Orientado a Objetivos',
    'Orientado a Resultados',
    'Orientado Al Logro',
    'Orientado Al Logro De Objetivos',
    'Origin',
    'Originlab',
    'Originpro',
    'Orion',
    'Oris',
    'Orpak',
    'Ortografía',
    'Os390',
    'Os400',
    'Osb',
    'Oscar',
    'Osciloscopio',
    'Oscommerce',
    'Ose2000',
    'Osirix',
    'Osticket',
    'Osx',
    'Otrs',
    'Outlook',
    'Ovation',
    'Overcall',
    'Oziexplorer',
    'Paciencia',
    'Paciencia e Insistencia',
    'Paciente',
    'Packet tracer',
    'Pacom',
    'Pactware',
    'Pagemaker',
    'Pages',
    'Paginas web',
    'Paint',
    'Paint Shop Pro',
    'Paint Tool Sai',
    'Painter',
    'Pajek',
    'Palm',
    'Paltec',
    'Pandora',
    'Panduit',
    'Paperless',
    'Paradox',
    'Participativo/a',
    'Particle Illusion',
    'Partner',
    'Pascal',
    'Pasión',
    'Pasión Por El Trabajo',
    'Past',
    'Pathfinder',
    'Pathloss',
    'Pavcad',
    'Pavivial',
    'Paws',
    'Paxer',
    'Payroll',
    'Payroll 4.8',
    'Pbasic',
    'Pcanywhere',
    'Pcgive',
    'Pcm600',
    'Pcom',
    'Pcs7',
    'Pdms',
    'Pds',
    'Peachtree',
    'Pedagogía',
    'Pegaso',
    'Pensamiento Analítico',
    'Pensamiento Creativo',
    'Pensamiento Crítico',
    'Pensamiento Estratégico',
    'Pensamiento Innovador',
    'Pensamiento Lógico',
    'Pensamiento Sistémico',
    'Pentaho',
    'Pentaho Data Integration',
    'Pentana',
    'Pentesting',
    'Peoplenet',
    'Peoplesoft',
    'Perfeccionista',
    'Pérgamo',
    'Periodismo',
    'Perl',
    'Perseverancia',
    'Perseverante',
    'Pershing',
    'Persistencia',
    'Persistencia Para Obtener Los Resultados',
    'Persistencia Para Obtener Los Resultados Deseados',
    'Persistente',
    'Persona Organizada',
    'Persona Proactiva',
    'Persona Responsable',
    'Personalidad',
    'Personalidad Amigable',
    'Perspicaz',
    'Persuasión',
    'Persuasivo/a',
    'Petrel',
    'Pfsense',
    'Pgadmin',
    'Phase',
    'Phase2',
    'Phoenics',
    'Phoenix',
    'Phonegap',
    'Photofiltre',
    'Photoimpact',
    'Photomodeler',
    'Photoprint',
    'Photoscan',
    'Photoscape',
    'Php',
    'Php 5',
    'Phpmyadmin',
    'Phpstorm',
    'Phreeqc',
    'Pi Processbook',
    'PI System',
    'Pibe',
    'Picasa',
    'Piktochart',
    'Pinacle',
    'Pinnacle',
    'Pinnacle Studio',
    'Pinterest',
    'Pintura',
    'Pipedrive',
    'Pipeflow',
    'Pipenet',
    'Pipephase',
    'Pipesim',
    'Piranesi',
    'Pivotal',
    'Pix4d',
    'Pixel',
    'Pixelmator',
    'Pkms',
    'Pl Sql',
    'Plan De Marketing',
    'Plan Ok',
    'Planeación',
    'Planeación Estratégica',
    'Planet',
    'Planex',
    'Planificación',
    'Planificación De La Producción',
    'Planificación De Mantenimiento',
    'Planificación De Proyectos',
    'Planificación Estratégica',
    'Planificación Financiera',
    'Planificado/a',
    'Planificador',
    'Planificadora',
    'Planificar',
    'Planner',
    'Planok',
    'Planut',
    'Planview',
    'Plasma',
    'Platino',
    'Plaxis',
    'Play Roll',
    'Plc',
    'Plcs',
    'Plecs',
    'Plesk',
    'Plex',
    'Plexos',
    'Plone',
    'Pls Cadd',
    'Plscadd',
    'Plsql',
    'Pmbok',
    'Pmbook',
    'Pmi',
    'Pmm',
    'Pmo',
    'Pmp',
    'Pms',
    'Pneusim',
    'Poder De Convencimiento',
    'Poder De Negociación',
    'Podio',
    'Polifuncional',
    'Polivalente',
    'Polycom',
    'Polymath',
    'Polyworks',
    'Pom',
    'Poo',
    'Poppy',
    'Portia',
    'Portugués',
    'Pos',
    'Poseidon',
    'Poser',
    'Positivismo',
    'Positivo/a',
    'Posone',
    'Postfix',
    'Postgis',
    'Postgresql',
    'Postman',
    'Potencial De Crecimiento',
    'Power Bi',
    'Powerbuilder',
    'Powercenter',
    'Powerdesigner',
    'Powerpivot',
    'Powerplay',
    'Powerpoint',
    'Powershell',
    'Powersieve',
    'Powersim',
    'Powerview',
    'Powerword',
    'Powerworld',
    'Powtoon',
    'Praat',
    'Práctico/a',
    'Pragmatic',
    'Pragmático',
    'Predicplan',
    'Predisposición Para Aprender',
    'Preference',
    'Preps',
    'Presea',
    'Presence',
    'Presentaciones Efectivas',
    'Pressto',
    'Prestashop',
    'Prestige',
    'Presto',
    'Presto 8.7',
    'Presto 8.8',
    'Prestore',
    'Presupuesto',
    'Presupuestos',
    'Preven',
    'Prevención De Riesgos',
    'Previred',
    'Prevsis',
    'Prezi',
    'Primaver P6',
    'Primavera',
    'Primavera 6',
    'Primavera P3',
    'Primavera P6',
    'Primavera Project',
    'Primavera Project P6',
    'Primavera Project Planner',
    'Primavera Project Planner P6',
    'Primefaces',
    'Primeros Auxilios',
    'Prinergy',
    'Prism',
    'Prism4',
    'Prisma',
    'Pro Actividad',
    'Pro Activo/a',
    'Proactiva Responsable',
    'Proactivanet',
    'Proactiveoffice',
    'Proactividad',
    'Proactividad e Iniciativa',
    'Proactivo/a',
    'Proaudit',
    'Probelt',
    'Probidad',
    'Problem Solving',
    'Procesamiento De Información',
    'Procesos',
    'Procesos De Negocio',
    'Processing',
    'Processmaker',
    'Procobol',
    'Procreate',
    'Producción',
    'Producción Audiovisual',
    'Producción De Eventos',
    'Product Management',
    'Product Manager',
    'Product Owner',
    'Productividad',
    'Productivo/a',
    'Proengineer',
    'Profactura',
    'Profesional',
    'Profesional Responsable',
    'Profesionalismo',
    'Profibus',
    'Profile',
    'Profit',
    'Profit Plus',
    'Profitplus',
    'Profitrace',
    'Programación Básica',
    'Programación orientada a Objetos',
    'Programación Web',
    'Programas básicos',
    'Programas Contables',
    'Programas de diseño',
    'Programas de edición',
    'Progress',
    'Proii',
    'Project',
    'Project 2000',
    'Project 2003',
    'Project 2007',
    'Project 2010',
    'Project 2013',
    'Project Management',
    'Projects',
    'Projectwise',
    'Prolab',
    'Prolijidad',
    'Prolijo/a',
    'Prolite',
    'Prolog',
    'Promob',
    'Promodel',
    'Promotora',
    'Pronexo',
    'Prontus',
    'Prophet',
    'Proshow',
    'Prosis',
    'Prosoft',
    'Prostyle',
    'Prosystem',
    'Protel',
    'Proteus',
    'Protheus',
    'Protocolos',
    'Protools',
    'Protopo',
    'Prototype',
    'Proview',
    'Provision',
    'Proxmox',
    'Proxy',
    'Proyectos',
    'Prtg',
    'Prudencia',
    'Prudente',
    'Pscad',
    'Pseint',
    'Psicodiagnóstico',
    'Psicología',
    'Psicología Clínica',
    'Psicoterapia',
    'Psim',
    'Psint',
    'Psoft',
    'Pspice',
    'Pspp',
    'Publicidad',
    'Published',
    'Publisher',
    'Pubmed',
    'Puedo Trabajar Bajo Presión',
    'Pulsar',
    'Puntual',
    'Puntualidad',
    'Puntualidad y responsabilidad',
    'Putty',
    'Pv Syst',
    'Pvelite',
    'Pvsol',
    'Pvsyst',
    'Pymetec',
    'Pymexsys',
    'Pymol',
    'Pyroll',
    'Python',
    'Qa',
    'Qad',
    'Qbasic',
    'Qbiz',
    'Qfiniti',
    'QGIS',
    'Qlickview',
    'Qliksense',
    'Qlikview',
    'Qmarket',
    'Qp Factory',
    'Qpfactory',
    'Qpro',
    'Quadrem',
    'Qualisys',
    'Qualtrics',
    'Quantrix',
    'Quantum',
    'Quanvert',
    'Quark',
    'Quarkxpress',
    'Quartz',
    'Query',
    'Quest',
    'Quickbase',
    'Quickbook',
    'Quickbooks',
    'Quicken',
    'Quicktime',
    'Química',
    'Quiter',
    'Qvet',
    'Qwantec',
    'r Project',
    'r Software',
    'Radan',
    'Radar',
    'Radatam',
    'Radian 6',
    'Radian6',
    'Radiance',
    'Radiofrecuencia',
    'Radiomobile',
    'Radius',
    'Radixx',
    'Radmin',
    'Radwin',
    'Rails',
    'Raisoft',
    'Raissa',
    'Ram',
    'Ramadvance',
    'Ramadvanse',
    'Random',
    'Randon',
    'Rápida Adaptación',
    'Rápida Adaptación a Los Cambios',
    'Rápida Capacidad De Aprendizaje',
    'Rápida Para Aprender',
    'Rapidez',
    'Rapidez De Aprendizaje',
    'Rapidez en Aprendizaje',
    'Rapidez Para Aprender',
    'Rapidminer',
    'Rápido Aprendizaje',
    'Rápido/a',
    'Raptor',
    'Raspberry',
    'Rational',
    'Rational Rose',
    'Rayén',
    'Razonamiento Analítico',
    'Razonamiento Lógico',
    'Razor',
    'Rce',
    'Rcweb',
    'React',
    'Reactjs',
    'Readsoft',
    'Realais',
    'Realflow',
    'Realización Audiovisual',
    'Reaper',
    'Reason',
    'Rebar',
    'Rebsol',
    'Recap',
    'Recepción',
    'Recepcionista',
    'Rech',
    'Reciber',
    'Reclutamiento',
    'Recmin',
    'Rector',
    'Recursos Humanos',
    'Redacción',
    'Redacción Creativa',
    'Redacción De Contenidos',
    'Redacción De Documentos',
    'Redacción De Informes',
    'Redacción De Informes Técnicos',
    'Redatam',
    'Redes Computacionales',
    'Redes de Datos',
    'Redes Inalambricas',
    'Redes Sociales',
    'Redes y Comunicaciones',
    'Redes y Telecomunicaciones',
    'Redhat',
    'Redis',
    'Redmine',
    'Redoc',
    'Reflection',
    'Reflex',
    'Reflexivo',
    'Regic',
    'Relación Con Clientes',
    'Relación Con Proveedores',
    'Relación Interpersonal',
    'Relación Interpersonales',
    'Relacionamiento',
    'Relaciones Humanas',
    'Relaciones Internacionales',
    'Relaciones Interpersonales',
    'Relaciones Laborales',
    'Relaciones Personales',
    'Relaciones Públicas',
    'Relaciones Sociales',
    'Relatoría',
    'Reliasoft',
    'Relux',
    'Rem700',
    'Remedy',
    'Remu',
    'Remuneraciones',
    'Reponedor',
    'Report',
    'Reportería',
    'Reportes',
    'Reporting',
    'Reporting Services',
    'Reports',
    'Reposición',
    'Reqlogic',
    'Res2dinv',
    'Reserve',
    'Resiber',
    'Resilencia',
    'Resilente',
    'Resiliencia',
    'Resistencia a La Presión',
    'Resistencia a Trabajar Bajo Presión',
    'Resistencia Al Trabajo Bajo Presión',
    'Resolución De Conflicto',
    'Resolución De Conflictos',
    'Resolución De Problemas',
    'Resolución De Problemas Complejos',
    'Resolume',
    'Resolutividad',
    'Resolutivo/a',
    'Resolver Problemas',
    'Respeto a Las Opiniones',
    'Respetuoso/a',
    'Responsabilidad',
    'Responsabilidad en El Trabajo',
    'Responsabilidad Laboral',
    'Responsabilidad Profesional',
    'Responsabilidad Social',
    'Responsabilidad Social Empresarial',
    'Responsable',
    'Responsable en El Trabajo',
    'Responsable Proactiva',
    'Responsable Puntual',
    'Responsables',
    'Rest',
    'Restbar',
    'Restó',
    'Retail',
    'Retailpro',
    'Retrospect',
    'Retscreen',
    'Reuters',
    'Revit',
    'Rezebra',
    'Rfid',
    'Rhino',
    'Rhino3d',
    'Rhinoceros',
    'Rhinoceros 3d',
    'Rhinoceros 4.0',
    'Rhinocerose',
    'Rhinos',
    'Rhodas',
    'Rhpro',
    'Richfaces',
    'Rigel',
    'Right Now',
    'Rigurosa',
    'Rigurosidad',
    'Ris',
    'Risa',
    'Risa 3d',
    'Risa3d',
    'Risk',
    'Risk Simulator',
    'Rm/Cobol',
    'Rmes',
    'Roadeng',
    'Roadnet',
    'Roadshow',
    'Roble',
    'Robohelp',
    'Robot',
    'Robotstudio',
    'Rocdata',
    'Rocfall',
    'Rockdata',
    'Rockfall',
    'Rocklab',
    'Rockplane',
    'Rockscience',
    'Rockwell',
    'Rockworks',
    'Rocky Dem',
    'Roclab',
    'Rocplane',
    'Rocscience',
    'Rocsience',
    'Roddiag',
    'Rolog',
    'Roscoe',
    'Rossoft',
    'Router',
    'Router Cisco',
    'Routers',
    'Routing',
    'Rpg',
    'Rpg400',
    'Rrhh',
    'Rrss',
    'Rslinx',
    'Rslogic',
    'Rslogix',
    'Rslogix 500',
    'Rslogix 5000',
    'Rslogix5',
    'Rslogix5000',
    'Rsnetworx',
    'Rstudio',
    'Rsview',
    'Rsview32',
    'Ruaumoko',
    'Ruby',
    'Ruby on Rails',
    'Rukan',
    'Runa',
    'Rup',
    'S10',
    'S400',
    'S7 200',
    'Saad',
    'Saber Escuchar',
    'Saber Trabajar en Equipo',
    'Sabini',
    'Sac',
    'Sacc',
    'Sae',
    'Saes',
    'Saeta',
    'Saf',
    'Safari',
    'Safe',
    'Safenet',
    'Safi',
    'Saga',
    'Sagaf',
    'Sage',
    'Sagerh',
    'Sagop',
    'Sagsit',
    'Saint',
    'Salesforce',
    'Saleslogix',
    'Salino',
    'Salomon',
    'Salud Ocupacional',
    'Sam',
    'Samac',
    'Samba',
    'Samcef',
    'Samplitude',
    'Samsung',
    'Sap',
    'Sap 6.0',
    'Sap Abap',
    'Sap Business One',
    'Sap Crm',
    'Sap Erp',
    'Sap Fi',
    'Sap Fico',
    'Sap Hana',
    'Sap Hcm',
    'Sap Hr',
    'Sap Mm',
    'Sap Netweaver',
    'Sap One',
    'Sap Pm',
    'Sap Portal',
    'Sap Ps',
    'Sap r/3',
    'Sap R3',
    'Sap Rrhh',
    'Sap Sd',
    'Sar',
    'Sas',
    'Sasplanet',
    'Sass',
    'Sat',
    'Satif',
    'Saturn',
    'Saturno',
    'Sav',
    'Saydex',
    'Scada',
    'Scala',
    'Sccm',
    'Scene',
    'Scheme',
    'Schooltrack',
    'Scilab',
    'Scl',
    'Scomp',
    'Scontab',
    'Scoring',
    'Scorm',
    'Scota',
    'Scratch',
    'Screen',
    'Screen3',
    'Scribus',
    'Scriptcase',
    'Scripting',
    'Scrum',
    'Scrum Master',
    'Sddp',
    'Sdh',
    'Sdl Trados',
    'Sdlx',
    'Sdt',
    'Se Trabajar Bajo Presión',
    'Sé Trabajar en Equipo',
    'Sebra',
    'Secretaria',
    'Secretaria Administrativa',
    'Secretariado',
    'Securecrt',
    'Sedlog',
    'See Electrical',
    'Seguridad',
    'Seguridad De La Información',
    'Seguridad Industrial',
    'Seguridad Informática',
    'Seguridad Laboral',
    'Seguridad Personal',
    'Seisan',
    'Seisimager',
    'Selección',
    'Selección De Personal',
    'Selenium',
    'Senainfo',
    'Senda',
    'Sendacaj',
    'Sendmail',
    'Senegocia',
    'Sentido De La Responsabilidad',
    'Sentido De Pertenencia',
    'Sentido De Responsabilidad',
    'Sentido De Urgencia',
    'Sentido Del Humor',
    'Seo',
    'Ser Proactivo',
    'Ser Responsable',
    'Ser Un Gran Apasionado Por El Trabajo',
    'Serato',
    'Seriedad',
    'Servicedesk',
    'Servicenow',
    'Servicial',
    'Servicio Al Cliente',
    'Servicio De Atención Al Cliente',
    'Servicio Militar Al Día',
    'Servicont',
    'Servipyme',
    'Serviremu',
    'Servlet',
    'Servlets',
    'Setroute',
    'Seven',
    'Sevevial',
    'Sewercad',
    'Sftland',
    'Sga',
    'Sgc',
    'Sgcas',
    'Sgdoc',
    'Sgems',
    'Sgi',
    'Sgp',
    'Sgu',
    'Sgusac',
    'Sharepoint',
    'Sharepoint 2010',
    'Shares',
    'Sharpdevelop',
    'Shazam',
    'Shell',
    'Shell Script',
    'Shift',
    'Shopify',
    'Shotplus',
    'Showcase',
    'Shrms',
    'Sia',
    'Siac',
    'Siadi',
    'Siaf',
    'Siag',
    'Siagf',
    'Siagj',
    'Siagri',
    'Sial',
    'Siap',
    'Siaper',
    'Sibel',
    'Sibelius',
    'Sic3pro',
    'Sica',
    'Sicap',
    'Sicare',
    'Sicas',
    'Sicel',
    'Sicex',
    'Sicla',
    'Sico',
    'Sicof',
    'Sicom',
    'Sicon',
    'Sicop',
    'Sicret',
    'Sicu',
    'Sidco',
    'Sidemar',
    'Sidewinder',
    'Sidexis',
    'Sidra',
    'Sidrep',
    'Sidunea',
    'Siebel',
    'Siemens',
    'Siesa',
    'Sifge',
    'Sifie',
    'Sig',
    'Siga',
    'Sigac',
    'Sigad',
    'Sigar',
    'Sigat',
    'Sigav',
    'Sigdp',
    'Sige',
    'Sigec',
    'Sigemap',
    'Sigep',
    'Siger',
    'Siges',
    'Sigesp',
    'Sigetra',
    'Sigfe',
    'Sigfe 2.0',
    'Sigges',
    'Sigic',
    'Sigma',
    'Sigmafine',
    'Sigmanest',
    'Sigmaplot',
    'Sigmastat',
    'Signature',
    'Sigo',
    'Sigop',
    'Sigper',
    'Sigri',
    'Sihot',
    'Sii',
    'Siief',
    'Siigo',
    'Silab',
    'Silicom',
    'Silverlight',
    'Simad',
    'Simapro',
    'Simatic',
    'Simbad',
    'Simef',
    'Simio',
    'Simocode',
    'Simpatía',
    'Simphony',
    'Simul 8',
    'Simul8',
    'Simulación',
    'Simulación De Procesos',
    'Simulink',
    'Sinab',
    'Sinacofi',
    'Sincera',
    'Sinco',
    'Sineduc',
    'Sinergia',
    'Sinergy',
    'Sinetsur',
    'Sip',
    'Sipec',
    'Sipecweb',
    'Siper',
    'Sipre',
    'Siprenet',
    'Sipro',
    'Sirh',
    'Sirion',
    'Sirius',
    'Sis',
    'Sisac',
    'Sisadmin',
    'Sisalud',
    'Siscap',
    'Siscat',
    'Siscel',
    'Sisco',
    'Siscoin',
    'Siscom',
    'Siscont',
    'Sisconta',
    'Siscop',
    'Sisdoc',
    'Sise',
    'Sisfrunet',
    'Sisgen',
    'Sisman',
    'Sismaule',
    'Sison',
    'Sisper',
    'Sispre',
    'Sisprev',
    'Sispubli',
    'Sisrem',
    'Sistelab',
    'Sistemas',
    'Sistemas Administrativos',
    'Sistemas Computacionales',
    'Sistemas de Contabilidad',
    'Sistemas De Gestión',
    'Sistemas De Información Geográfica',
    'Sistrat',
    'Sisve',
    'Sisveg',
    'Sisven',
    'Sisweb',
    'Sitci',
    'Sitefinity',
    'Sitfa',
    'Sitla',
    'Sitrack',
    'Sitrel',
    'Situr',
    'Six Sigma',
    'Sixbell',
    'Sixtina',
    'Sketch',
    'Sketchbook',
    'SketchUp',
    'Sketchup 8',
    'Sketchup Pro',
    'Skualo',
    'Skype',
    'Slack',
    'Slide',
    'Slope',
    'Smallword',
    'Smallworld',
    'Smart',
    'Smart Plant 3d',
    'Smart Stream',
    'Smartboard',
    'Smartdraw',
    'Smartem',
    'Smarterm',
    'Smartflex',
    'Smartplant',
    'Smartplant 3d',
    'Smartpls',
    'Smartsheet',
    'Smartsketch',
    'Smartstream',
    'Smartview',
    'Smarty',
    'Smc',
    'Smile',
    'Snagit',
    'Snmp',
    'Snmpc',
    'Snort',
    'Soa',
    'Soap',
    'Soapui',
    'Sociabilidad',
    'Sociable',
    'Social',
    'Social Media',
    'Socialbakers',
    'Socialbro',
    'Sociales',
    'Socrative',
    'Sofcargo',
    'Sofcon',
    'Sofistik',
    'Sofnet',
    'Softcargo',
    'Softexpert',
    'Softguard',
    'Softland',
    'Softlider',
    'Softline',
    'Softmas',
    'Softmatica',
    'Softnet',
    'Softonic',
    'Softphone',
    'Softram',
    'Softrestaurant',
    'Softwarevulcan',
    'Sofware98',
    'Solaris',
    'Solarwinds',
    'Solclic',
    'Soldador',
    'Soldador Calificado',
    'Soldadura',
    'Solgest',
    'Solid Age',
    'Solid Works',
    'Solidaridad',
    'Solidario/a',
    'Solidege',
    'Solidworks',
    'Soliworks',
    'Solman',
    'Solnet',
    'Solomon',
    'Solución De Conflictos',
    'Solución De Problemas',
    'Solucionar Problemas',
    'Solver',
    'Somachine',
    'Somove',
    'Sonar',
    'Sonarqube',
    'Sonicwall',
    'Sony Vegas',
    'Sophos',
    'Soporte',
    'Soporte Computacional',
    'Soporte Técnico',
    'Soptur',
    'Soundforge',
    'Soundplan',
    'Soundtrack',
    'Soundtrack Pro',
    'Sourcesafe',
    'Soy Proactivo/a',
    'Soy Puntual',
    'Soy Responsable',
    'Soy Una Persona Pro Activa',
    'Soy Una Persona Proactiva',
    'Soy Una Persona Responsable',
    'Soy una persona responsable y proactiva',
    'Spaceclaim',
    'Spaceman',
    'Spad',
    'Spark',
    'Spectralab',
    'Spectrum',
    'Sphinx',
    'Spice',
    'Split',
    'Splunk',
    'Splus',
    'Spoolgen',
    'Spotfire',
    'Spr',
    'Spring Framework',
    'Spring Mvc',
    'Sproutsocial',
    'Sps',
    'SPSS',
    'Spss Modeler',
    'Spss Statistics',
    'Sql',
    'Sql 2000',
    'Sql 2005',
    'Sql 2008',
    'Sql Developer',
    'Sql Navigator',
    'Sql Oracle',
    'Sql Plus',
    'Sql Server 2000',
    'Sql Server 2005',
    'Sql Server 2008',
    'Sql Server 2008 R2',
    'Sql Server 2012',
    'Sql Server 7.0',
    'Sql Server Management Studio',
    'Sqlite',
    'Sqlplus',
    'Sqlyog',
    'Squid',
    'Srm',
    'Srx',
    'Ssas',
    'Ssis',
    'Ssrs',
    'Staad',
    'Starlims',
    'Staroffice',
    'Starter',
    'Staruml',
    'Stata',
    'Statfit',
    'Statgraphics',
    'Statistic',
    'Statistica',
    'Statistical',
    'Statistics',
    'Statistix',
    'Stats',
    'Steinberg Cubase',
    'Stella',
    'Stellar',
    'Step 5',
    'Step 7',
    'Step 7 Microwin',
    'Step7',
    'Stereonet',
    'Stock Down',
    'Stockdown',
    'Storage',
    'Storyline',
    'Stradivarius',
    'Strata',
    'Strata 3d',
    'Strategic Planning',
    'Strater',
    'Streaming',
    'Structure',
    'Strumis',
    'Struts',
    'Struts2',
    'Struxure',
    'Stylus',
    'Subcontrataley',
    'Sublime',
    'Sublimetext',
    'Subtitle Workshop',
    'Subversion',
    'Success Factors',
    'Successfactors',
    'SugarCRM',
    'Suite Adobe Cc',
    'Suite Adobe Cs5',
    'Suite Adobe Cs6',
    'Suite Macromedia',
    'Suite Microsoft Office',
    'Suite Office',
    'Suite2000',
    'Sun',
    'Sun System',
    'Sun Systems',
    'Sunsystem',
    'Sunsystems',
    'Superación',
    'Superior Control',
    'Superpro',
    'Superpro Designer',
    'Superproject',
    'Supervisión',
    'Supervisión De Personal',
    'Supervisor',
    'Supply Chain',
    'Supply Chain Management',
    'Surfcam',
    'Surfer',
    'Surfer 8',
    'Surpac',
    'Survey',
    'Surveymonkey',
    'Svn',
    'Swan',
    'Swedge',
    'Swift',
    'Swift 3d',
    'Swift3d',
    'Swish',
    'Swish 2.0',
    'Swish Max',
    'Swishmax',
    'Switch',
    'Switches',
    'Switchfly',
    'Switching',
    'Swmm',
    'Sybase',
    'Sybase Power Designer',
    'Sydra',
    'Symantec',
    'Symbian',
    'Symfony',
    'Symfony2',
    'Symphony',
    'Symposium',
    'Synapse',
    'Syncomm',
    'Synergia',
    'Synergy',
    'Sysaid',
    'Sysbase',
    'Syscol',
    'Syscom',
    'Syscont',
    'Syseva',
    'Sysgestión',
    'Syslab',
    'Syslog',
    'Sysman',
    'Sysomos',
    'Systat',
    'Syteline',
    'T2000',
    'Tabla Docsis',
    'Tableau',
    'Tableau Software',
    'Tactica',
    'Talana',
    'Talend',
    'Taleo',
    'Talpac',
    'Tandem',
    'Tango',
    'Tango Gestión',
    'Tank',
    'Target',
    'Tas',
    'Taurus',
    'Tc 2000',
    'Tc2000',
    'Tct',
    'Team Foundation Server',
    'Team Leadership',
    'Team Mate',
    'Team Player',
    'Team Work',
    'Teammate',
    'Teamviewer',
    'Teamwork',
    'Techfood',
    'Tecmedica',
    'Técnicas De Negociación',
    'Técnicas De Ventas',
    'Tecnisa',
    'Tecnocaja',
    'Tecnologías De La Información',
    'Tecnosoft',
    'Tecplot',
    'Tekla',
    'Tekla Structures',
    'Teknisa',
    'Tele Marketing',
    'Telecomunicaciones',
    'Teledetección',
    'Telemagic',
    'Telepregon',
    'Telereport',
    'Telerik',
    'Telescript',
    'Telesoft',
    'Telnet',
    'Tempest',
    'Templanza',
    'Tempo',
    'Tenacidad',
    'Tenaz',
    'Tener La Capacidad De Negociar',
    'Tengo Iniciativa',
    'Tensorflow',
    'Teradata',
    'Terminal Financiero',
    'Terramodel',
    'Terraspec',
    'Terrasync',
    'Terrset',
    'Teslink',
    'Tesorería',
    'Testing',
    'Testlink',
    'Texmaker',
    'Thalamus',
    'Therm',
    'Think Cell',
    'Thinkcell',
    'Thomson Reuters',
    'Thunderbird',
    'Tia Portal Siemens',
    'Tiaportal',
    'Tibco',
    'Ticares',
    'Tilos',
    'Tina',
    'Tinyterm',
    'Tivoli',
    'Tma',
    'Tms',
    'Tn3270',
    'Tnt Mips',
    'Tntmips',
    'Toad',
    'Toad for Oracle',
    'Togaf',
    'Tolerancia',
    'Tolerancia a La Frustración',
    'Tolerancia a La Presión',
    'Tolerancia Al Estrés',
    'Tolerancia Al Fracaso',
    'Tolerancia Al Trabajo Bajo Presión',
    'Tolerante',
    'Tolerante a La Frustración',
    'Toma De Decisiones',
    'Toolbox',
    'Toon Boom',
    'Top Solid',
    'Topocal',
    'Topograph',
    'Topsolid',
    'Tora',
    'Toresa',
    'Torpedo',
    'TortoiseSVN',
    'Tosmana',
    'Total',
    'Totalpack',
    'Totalview',
    'Toteat',
    'Totvs',
    'Tour Plan',
    'Tourplan',
    'Tower',
    'Tpm',
    'Trabaja en Equipo',
    'Trabajador en Equipo',
    'Trabajar Bajo Presión',
    'Trabajar en Equipo',
    'Trabajar en Grupo',
    'Trabajo Bajo Presión',
    'Trabajo Bien Bajo Presión',
    'Trabajo Bien en Equipo',
    'Trabajo Colaborativo',
    'Trabajo Comunitario',
    'Trabajo Con Equipos Multidisciplinarios',
    'Trabajo De Equipo',
    'Trabajo en Altura',
    'Trabajo en Equipo',
    'Trabajo en Equipo e Individual',
    'Trabajo en Equipo Multidisciplinario',
    'Trabajo en Equipo y Cooperación',
    'Trabajo en Equipos Multidisciplinarios',
    'Trabajo en Grupo',
    'Trabajo en Terreno',
    'Trabajo Grupal',
    'Trabajo Multidisciplinario',
    'Trabajo Por Objetivos',
    'Trabajo Seguro',
    'Track',
    'Trackare',
    'Trackcare',
    'Tracking',
    'Trackwise',
    'Trade Marketing',
    'Trados',
    'Traducción',
    'Trakcare',
    'Traktor',
    'Transact Sql',
    'Transactor',
    'Transbank',
    'Transcad',
    'Transcomex',
    'Transformación Digital',
    'Transit',
    'Transparencia',
    'Transparente',
    'Transtecnia',
    'Transyt',
    'Trato Con Clientes',
    'Trello',
    'Tricalc',
    'Tricaster',
    'Trnsys',
    'Tronweb',
    'Troubleshooting',
    'Truck',
    'Tso',
    'Tuneup Utilities',
    'Turbo c',
    'Turbo C++',
    'Turbo Pascal',
    'Turnex',
    'Tuxedo',
    'Tv Data',
    'Tvdata',
    'Tweetdeck',
    'TwidoSuite',
    'Twinmotion',
    'Twitter',
    'Txsus',
    'Typescript',
    'Typo 3',
    'Typo3',
    'U2000',
    'Ubiquiti',
    'Ubuntu',
    'Ucinet',
    'Uipath',
    'Ulead',
    'Ultimus',
    'Ultraedit',
    'Ultragestión',
    'Ultrapipe',
    'Umas',
    'Uml',
    'Umts',
    'Ungasoft',
    'Unicorn',
    'Unicornio',
    'Uniface',
    'Unifica',
    'Unigraphics',
    'Unipre',
    'Unisof',
    'Unisoft',
    'Unisys',
    'Unity',
    'Unity 3d',
    'Unity Pro',
    'Unitypro',
    'Unix',
    'Unscrambler',
    'Unwedge',
    'Unypre',
    'Unyrem',
    'Unysoft',
    'Utilsoft',
    'Utorrent',
    'Uxpos',
    'V-Ray',
    'Vacico',
    'Vagrant',
    'Valery',
    'Vantage',
    'Vantive',
    'Vax',
    'Vb6',
    'Vba',
    'Vbasic',
    'Vbscript',
    'Vector',
    'Vectorworks',
    'Veeam',
    'Vel2000',
    'Velneo',
    'Velocity',
    'Vendedora',
    'Venpri',
    'Vensim',
    'Venta Consultiva',
    'Ventas',
    'Ventas Técnicas',
    'Ventix',
    'Ventor',
    'Ventsim',
    'Ventyx',
    'Verbal',
    'Verilog',
    'Veritas',
    'Versapro',
    'Versátil',
    'Versatilidad',
    'Versionamiento',
    'Vexport',
    'Vhdl',
    'Vhms',
    'Vias',
    'Vicidial',
    'Videograph',
    'Videopad',
    'Videoscribe',
    'Vijeo',
    'Vims',
    'Vinculación Con El Medio',
    'Virtual Dj',
    'Virtualbox',
    'Virtualdj',
    'Visaer',
    'Visio',
    'Vision',
    'Visión Estratégica',
    'Visionario/a',
    'Vissim',
    'Visual',
    'Visual Basic',
    'Visual Basic 5.0',
    'Visual Basic 6',
    'Visual Basic 6.0',
    'Visual Basic.net',
    'Visual C#',
    'Visual C++',
    'Visual Dent',
    'Visual Fox Pro',
    'Visual Foxpro',
    'Visual Jobshop',
    'Visual Manufacturing',
    'Visual Merchandising',
    'Visual Modflow',
    'Visual Paradigm',
    'Visual Studio',
    'Visual Studio 2005',
    'Visual Studio 2008',
    'Visual Studio 2010',
    'Visual Studio 2012',
    'Visual Studio 2013',
    'Visual Studio C#',
    'Visual Studio.net',
    'Visualdent',
    'Vizio',
    'Vizrt',
    'Vms',
    'Vmware',
    'Vmware Esxi',
    'Vmware Vsphere',
    'Vmware Workstation',
    'Vnc',
    'Vnetpc',
    'Vocación',
    'Vocación Al Servicio',
    'Vocación De Servicio',
    'Vocalcom',
    'Voip',
    'Voluntad',
    'Voluntad De Actuar',
    'Voyager',
    'Vpn',
    'Vtex',
    'Vtiger',
    'Vuejs',
    'Vulcan',
    'Vulcan 7.5',
    'Vulkan',
    'W2000',
    'Wacom',
    'Wamp',
    'Wampserver',
    'Wareflow',
    'Was',
    'Wasp',
    'Watchguard',
    'Watercad',
    'Wavelab',
    'Wcadi',
    'Wcdma',
    'Wcf',
    'Weap',
    'Webclass',
    'Webcontrol',
    'Webex',
    'Weblogic',
    'Webmail',
    'Webquest',
    'Websal',
    'Websense',
    'Webservice',
    'Websphere',
    'Websphere Application Server',
    'Weebly',
    'Weibull',
    'Weka',
    'Wellcad',
    'Wellflo',
    'Wenco',
    'Whats Best',
    'Whatsapp',
    'Whittle',
    'Who Anthro',
    'Wifislax',
    'Wikipedia',
    'Wilcom',
    'Wimax',
    'Wimper',
    'Win7',
    'Winamp',
    'Winbugs',
    'Wincc',
    'Wind',
    'Windev',
    'Windfarmer',
    'Windmil',
    'Windographer',
    'Windows Millenium',
    'Windows Movie Maker',
    'Windows Server',
    'Windows Server 2003',
    'Windows Server 2008',
    'Windows Server 2008 R2',
    'Windows Server 2012',
    'Windpro',
    'Windte',
    'Winedt',
    'Winfiol',
    'Wingems',
    'Wingpc',
    'Winhotel',
    'Winisis',
    'Winlunch',
    'Winmap',
    'Winner',
    'Winper',
    'Winpro',
    'Winproladder',
    'Winproyect',
    'Winqsb',
    'Winrar',
    'Winscp',
    'Winsig',
    'Winstat',
    'Winsurf',
    'Wintel',
    'Winunisoft',
    'Winxp',
    'Winzip',
    'Wipfrag',
    'Wirecast',
    'Wireless',
    'Wireshark',
    'Wiris',
    'Wisetrack',
    'Witness',
    'Wix',
    'Wizard',
    'Wmos',
    'Wms',
    'Wmstek',
    'Wonderware',
    'Woocommerce',
    'Word 2000',
    'Word 2003',
    'Word 2007',
    'Word 2010',
    'Word 2013',
    'Wordfast',
    'Wordperfect',
    'Wordpress',
    'Wordstar',
    'Worflow',
    'Work Flow',
    'Workbench',
    'Workday',
    'Workflow',
    'Workflows',
    'Workforce',
    'Workload',
    'Workmate',
    'Works',
    'Workshop',
    'Workstation',
    'Worldspan',
    'Wplsoft',
    'Wrike',
    'Wrplot',
    'Wsus',
    'Xamarin',
    'Xampp',
    'Xara',
    'Xbench',
    'Xcalibur',
    'Xcelsius',
    'Xcode',
    'Xenserver',
    'Xeras',
    'XHTML',
    'Xilab',
    'Xilinx',
    'Xlpro',
    'Xlstat',
    'Xmind',
    'Xml',
    'Xmlspy',
    'Xnear',
    'Xpert',
    'Xpress',
    'Xpyme',
    'Xsl',
    'Xslt',
    'Xsteel',
    'Yasper',
    'Youtube',
    'Zabbix',
    'Zap',
    'Zararadio',
    'Zbrush',
    'Zebra',
    'Zelio Soft',
    'Zendesk',
    'Zenoss',
    'Zeus',
    'Zigbee',
    'Zimbra',
    'Zimpl',
    'Zoho',
    'Zoho Crm',
    'Zone Alarm',
    'Zoom',
    'Zorba',
    'Zotero',
    'Zwcad',
    'Zyght',
];
