<?php

/**
 * Instituciones de educación superior de Chile.
 *
 * @return array<int, string>
 */
return [
    'Academia Politécnica Militar ( ACAPOMIL )',
    'Academia Politécnica Naval ( APOLINAV )',
    'Armada de Chile',
    'Centro de Educación y Capacitación de la Universidad Católica del Norte ( CEDUC UCN )',
    'Centro Educacional de Alta Tecnología ( CEAT )',
    'CFT ABACUS ITC',
    'CFT Academia Chilena De Yoga',
    'CFT Accioma',
    'CFT Acuario Data de Santiago',
    'CFT Alemán de Viña del Mar',
    'CFT Alexander Von Humboldt',
    'CFT Alfa',
    'CFT Alpes ( ALPESCFT )',
    'CFT Andrés Bello',
    'CFT AquaTech',
    'CFT Asiste',
    'CFT Austral',
    'CFT Barros Arana',
    'CFT Canon',
    'CFT Carlos Thielemann Martin',
    'CFT Cedecom',
    'CFT CEDEP',
    'CFT CEFONOR',
    'CFT CEITEC',
    'CFT Cenafom',
    'CFT CENCO',
    'CFT Centro de Enseñanza de Alta Costura Paulina Diard',
    'CFT Centro de Estudios Navieros Concepción',
    'CFT Centro de Estudios Paramédicos de Santiago ( CEPSA )',
    'CFT Centro de Estudios Turísticos ( CET )',
    'CFT Centro de Formación Empresarial IFE',
    'CFT Centro Tecnológico Superior INFOMED',
    'CFT CEPA de la III Región',
    'CFT CEPONAL',
    'CFT Chileno-Norteamericano',
    'CFT CIARTES',
    'CFT CIMA de Rengo',
    'CFT COLCHAGUA',
    'CFT Crecic',
    'CFT Crownliet',
    'CFT de Educación Superior Agrícola Miguel Covarrubias Valdés',
    'CFT de la Industria Gráfica ( INGRAF )',
    'CFT De La Región De Antofagasta',
    'CFT De La Región De Arica Y Parinacota',
    'CFT De La Región De Atacama',
    'CFT De La Región De Aysén Del General Carlos Ibáñez Del Campo',
    'CFT De La Región De Coquimbo',
    'CFT De La Región De La Araucanía',
    'CFT De La Región De Los Lagos',
    'CFT De La Región De Los Ríos',
    'CFT De La Región De Magallanes Y Antártica Chilena',
    'CFT De La Región De Valparaíso',
    'CFT De La Región Del Bío Bio',
    "CFT De La Región Del Libertador General Bernardo O'Higgins",
    'CFT De La Región Del Maule',
    'CFT De La Región Metropolitana De Santiago',
    'CFT de la Universidad de Valparaíso ( CFT UV )',
    'CFT de la Universidad Mayor ( MAGNOS )',
    'CFT De Los Establecimientos Nacionales De Educación Cáritas-Chile ( ENAC )',
    'CFT de Tarapacá',
    'CFT del Medio Ambiente ( IDMA )',
    'CFT Diego Portales',
    'CFT ECATEMA',
    'CFT Educación y Capacitación ( EDUCAP )',
    'CFT El Libertador',
    'CFT El Roble',
    'CFT English Language Training Center ( ELTC )',
    'CFT Escuela Culinaria Francesa ( ECOLE )',
    'CFT Escuela de Administración Agrícola de la SNA',
    'CFT Escuela de Altos Estudios de la Comunicación y Educación ( EACE )',
    'CFT Escuela de Artes Aplicadas Oficios del Fuego',
    'CFT Escuela de Capacitación de Ocupaciones Laborales',
    'CFT Escuela de Ciencias Turísticas e Idiomas ( EDECTI )',
    'CFT Escuela de Comercio',
    'CFT Escuela de Contabilidad y Administración - Centro de Estudios Contables ( CFT ECACEC )',
    'CFT Escuela de Interpretes INCENI',
    'CFT Escuela Nacional de Capacitación ( CFT ENAC )',
    'CFT Escuela Superior de Administración de Negocios ( ESANE )',
    'CFT Escuela Superior de Administración de Negocios del Norte ( ESANE del Norte )',
    'CFT Escuela Superior de Comercio Exterior ( ESCE )',
    'CFT Escuela Superior de Comercio Exterior de Santiago ( ESCES )',
    'CFT ESI',
    'CFT Esperanza Joven',
    'CFT Estatal Tarapacá',
    'CFT Estudio Profesor Valero',
    'CFT ESUCOMEX',
    'CFT Eugenio González Rojas',
    'CFT Finning',
    'CFT FIRENZE',
    'CFT FONTANAR',
    'CFT Genoveva Guarniero',
    'CFT ICADE',
    'CFT ICEL',
    'CFT Ignacio Domeyko',
    'CFT INCOR',
    'CFT INFOEDUC',
    'CFT INSES',
    'CFT Instituto Central De Capacitación Educacional ( ICCE )',
    'CFT Instituto Chileno Alemán de Cultura de San Antonio',
    'CFT Instituto Chileno Británico de Concepción',
    'CFT Instituto de Secretariado ( INSEC )',
    'CFT Instituto de Técnicas Turísticas, Hoteleras y Gastronómicas ( INTECTUR )',
    'CFT Instituto INTEC',
    'CFT Instituto Politécnico de la Universidad De Chile ( ITPUCH )',
    'CFT Instituto Superior Alemán De Comercio ( INSALCO )',
    'CFT Instituto Superior de Computación',
    'CFT Instituto Superior de Electrónica Gamma',
    'CFT Instituto Tecnológico de Chile ( ITC )',
    'CFT International House',
    'CFT INTESAN',
    'CFT IPROSEC',
    'CFT ITESA',
    'CFT ITUR',
    'CFT Javiera Carrera',
    'CFT Jhon F Kennedy',
    'CFT Jorge Alvarez Echeverría',
    'CFT Juan Bohon',
    'CFT La Araucana',
    'CFT La Calera',
    'CFT Laplace',
    'CFT Los Fundadores',
    'CFT Los Lagos',
    'CFT Los Leones',
    'CFT Lota Arauco',
    'CFT Luis Alberto Vera',
    'CFT Manpower',
    'CFT Massachusetts',
    'CFT Osorno',
    'CFT ProAndes',
    'CFT Prodata',
    'CFT PROFASOC',
    'CFT PROTEC',
    'CFT PUCV',
    'CFT PUKARA',
    'CFT Salesianos Don Bosco',
    'CFT San Agustín',
    'CFT San Alonso',
    'CFT San Patricio',
    'CFT Santa María del Trabajo',
    'CFT Santo Tomás ( CFT ST )',
    'CFT Simón Bolivar',
    'CFT SOEDUC Aconcagua',
    'CFT SOEDUC La Ligua',
    'CFT SOESTA',
    'CFT Tecnologías Contemporaneas ( TECCON )',
    'CFT Teodoro Wickel Kluwen',
    'CFT Umbrale de Santiago',
    'CFT Universidad Tecnológica Metropolitana ( CFT UTEM )',
    'CFT Valle Central',
    'CFT y Capacitación CEFOTEC',
    'CFT ZIPTER',
    'DuocUC',
    'Escuela de Aviación',
    'Escuela de Carabineros',
    'Escuela de Comunicación Mónica Herrera',
    'Escuela de Ingeniería Naval',
    'Escuela de Investigaciones ( PDI )',
    'Escuela de la Fuerza Aérea de Chile ( FACH )',
    'Escuela de Locutores de Chile',
    'Escuela de Medicina V Región',
    'Escuela de Negocios Española IEDE',
    'Escuela Militar',
    'Escuela Naval',
    'Estudios Superiores de la Empresa ( ESE )',
    'Fundación Emplea',
    'INACAP',
    'Instituto del Medio Ambiente - IDMA',
    'Instituto Profesional Cicerón',
    'Instituto Profesional Instituto Nacional Del Fútbol ( INAF )',
    'Instituto Profesional San Sebastián ( IPSS )',
    'IP Adventista ( IPA )',
    'IP Agrario Adolfo Matthei',
    'IP AIEP',
    'IP Alemán Wilhelm Von Humboldt',
    'IP Alpes',
    'IP Andalien',
    'IP Asociación Chilena de Seguridad ( IPACHS )',
    'IP Campus',
    'IP Carlos Casanueva',
    'IP CEC',
    'IP Centro de Informática e Ingeniería de Sistemas en Administración ( CIISA )',
    'IP Centro de Instrucción de Aeronáutica Civil Cenafom',
    'IP CEPECH',
    'IP Chileno Británico de Cultura',
    'IP Chileno Norteamericano',
    'IP Concepción',
    'IP de Arte y Comunicación ARCOS ( ARCOS )',
    'IP de Artes Escenicas Karen Connolly',
    'IP de Chile ( IPCHILE )',
    'IP de Ciencias de la Computación Acuario Data',
    'IP de Ciencias y Artes ( INCACEA )',
    'IP de Ciencias y Educación Helen Keller',
    'IP de Escuela Nacional de Capacitación ( IP ENAC )',
    'IP de Formación Empresarial',
    'IP de las Comunicaciones PROCOM',
    'IP de Los Angeles',
    'IP del Pacífico',
    'IP Diego Portales',
    'IP Dr. Virginio Gómez G.',
    'IP ECACEC',
    'IP Escuela Americana de Traductores e Intérpretes ( EATRI )',
    'IP Escuela de Cine de Chile',
    'IP Escuela de Comercio de Santiago',
    'IP Escuela de Contadores Auditores de Santiago ( ECAS )',
    'IP Escuela de Marina Mercante Piloto Pardo',
    'IP Escuela Latinoamericana de Idiomas ( ELADI )',
    'IP Escuela Moderna de Música ( EMODERNA )',
    'IP Escuela Nacional de Relaciones Públicas',
    'IP ESUCOMEX',
    'IP Galdames ( IPG )',
    'IP Hogar Catequístico',
    'IP IACC',
    'IP INDAE',
    'IP Instituto de Estudios Bancarios Guillermo Subercaseaux',
    'IP Instituto Internacional de Artes Culinarias y Servicios ( CULINARY )',
    'IP Instituto Nacional del Fútbol ( INAF )',
    'IP La Araucana',
    'IP Latinoamericano de Comercio Exterior ( IPLACEX )',
    'IP Libertador de Los Andes ( IPLA )',
    'IP Los Lagos ( IPLOSLAGOS )',
    'IP Los Leones ( IPLEONES )',
    'IP Luis Galdames',
    'IP Manpower',
    'IP Projazz',
    'IP Providencia ( IPP )',
    'IP San Bartolomé de La Serena',
    'IP Santo Tomás ( IPSANTOTOMAS )',
    'IP Superior de Electrónica Gamma',
    'IP Teatro La Casa',
    'IP Valle Central',
    'IP Vertical',
    'Pontificia Universidad Católica de Chile ( PUC )',
    'Pontificia Universidad Católica de Valparaíso ( PUCV )',
    'Universidad Academia de Humanismo Cristiano ( UAHC )',
    'Universidad Adolfo Ibañez ( UAI )',
    'Universidad Adventista de Chile ( UNACH )',
    'Universidad Alberto Hurtado ( UAH )',
    'Universidad Alonso de Ovalle',
    'Universidad Andrés Bello ( UNAB )',
    'Universidad Arturo Prat ( UNAP )',
    'Universidad Austral de Chile ( UACH )',
    'Universidad Autónoma de Chile ( UA )',
    'Universidad Autónoma del Sur',
    "Universidad Bernardo O'Higgins ( UBO )",
    'Universidad Bolivariana ( UB )',
    'Universidad Católica Blas Cañas',
    'Universidad Católica Cardenal Raúl Silva Henríquez ( UCSH )',
    'Universidad Católica de la Santísima Concepción ( UCSC )',
    'Universidad Católica de Temuco ( UCT )',
    'Universidad Católica del Maule ( UCM )',
    'Universidad Católica del Norte ( UCN )',
    'Universidad Central de Chile ( UCEN )',
    'Universidad Chileno Británica de Cultura ( UCBC )',
    'Universidad Ciencias de la Informática ( UCINF )',
    'Universidad de Aconcagua ( UAC )',
    'Universidad de Antofagasta ( UANTOF )',
    'Universidad de Arte y Ciencias Sociales Arcis ( ARCIS )',
    'Universidad de Artes, Ciencias y Comunicación ( UNIACC )',
    'Universidad de Atacama ( UDA )',
    'Universidad De Aysén ( UAY )',
    'Universidad de Chile ( UCH )',
    'Universidad de Concepción ( UDEC )',
    'Universidad de la Frontera ( UFRO )',
    'Universidad de la Serena ( USERENA )',
    'Universidad de las Américas ( UDLA )',
    'Universidad de los Andes ( UANDES )',
    'Universidad de Los Lagos ( ULAGOS )',
    'Universidad de Magallanes ( UMAG )',
    "Universidad De O'Higgins ( UOH )",
    'Universidad de Playa Ancha de Ciencias de la Educación ( UPLA )',
    'Universidad de Puerto Varas',
    'Universidad de San Andrés',
    'Universidad de Santiago de Chile ( USACH )',
    'Universidad de Talca ( UTALCA )',
    'Universidad de Tarapacá ( UTA )',
    'Universidad de Valparaíso ( UV )',
    'Universidad de Viña del Mar ( UVM )',
    'Universidad del Alba',
    'Universidad del Bío Bío ( UBB )',
    'Universidad del Desarrollo ( UDD )',
    'Universidad del Mar',
    'Universidad del Pacífico',
    'Universidad Diego Portales ( UDP )',
    'Universidad Educares',
    'Universidad Finis Terrae ( UFT )',
    'Universidad Francisco de Aguirre de la Serena',
    'Universidad Francisco de Vitoria',
    'Universidad Gabriela Mistral ( UGM )',
    'Universidad Iberoamericana de Ciencias y Tecnología ( UNICYT )',
    'Universidad Internacional SEK ( USEK )',
    'Universidad La República ( ULARE )',
    'Universidad Las Condes ( ULASCONDES )',
    'Universidad Los Leones ( ULL )',
    'Universidad Mariano Egaña',
    'Universidad Marítima de Chile ( MARITIMA )',
    'Universidad Mayor ( UMAYOR )',
    'Universidad Metropolitana de Ciencias de la Educación ( UMCE )',
    'Universidad Miguel de Cervantes ( UMC )',
    'Universidad Pedro de Valdivia ( UPV )',
    'Universidad Regional San Marcos ( URSM )',
    'Universidad San Sebastián ( USS )',
    'Universidad Santo Tomás ( UST )',
    'Universidad Técnica Federico Santa María ( USM )',
    'Universidad Tecnológica de Chile INACAP',
    'Universidad Tecnológica Metropolitana ( UTEM )',
    'Universidad Tecnológica Vicente Pérez Rosales ( PEREZ ROSALEZ )',
    'Otra Institución',
];
